### ISSUE TITLE
Configurable Settings Options Per World

### ISSUE THREAD

**Issue by MapleFighter** [np98765/BattleKits#10]
Since BattleKits should have everything configurable, config options should be configurable too! Allow all options in the config to be modified per world. This way Multi-world servers can utilize the great features BattleKits.

**Comment by lol768** [comment]
Proposed structure:
global.yml -- overriden by world_name.yml files (which the user must create)
kits.yml -- All kits in a nice compact file

**Comment by MapleFighter** [comment]
Yea, kits.yml would be a lot better than in the config.

**Comment by lol768** [comment]
@MapleFighter It was np98765's idea, and it would probably neaten up the config quite a bit.

**Comment by np98765** [comment]
I like the idea of global settings, with per-world overrides.  I'm sure that many people using this plugin have set up a KitPvP-only world, and don't want the features throughout their entire server.

The dataFolder should look something like:
config.yml
kits.yml
global.yml
<worldName>.yml  for each world

As for the kits.yml, I've had the idea for a while but haven't actually gotten around to implementing it.  At this point, I doubt I'll get to do it, but if I have any free moments over the weekend I can start/edit/finish whatever progress there is.

**Comment by lol768** [comment]
https://github.com/np98765/BattleKits/commit/7a781a3eed84fa001071c937b0888f463ce1b009

I've started to do this, unsure about how to proceed with world-specific configs though. I'd prefer to stick it all in the global.yml file:

``` yaml
world-settings:
    world_nether:
        #some settings
    world_the_end:
        #more settings
```

**Comment by lol768** [comment]
Outsource testing to community: http://dev.bukkit.org/server-mods/battlekits/?comment=169

**Comment by MapleFighter** [comment]
NIce, can I help test it out?

**Comment by lol768** [comment]
Go for it :)

**Comment by lol768** [comment]
Actually, Jenkins has failed. One min

**Comment by lol768** [comment]
Fixed. Check your PM :smile:

**Comment by lol768** [comment]
https://github.com/np98765/BattleKits/commit/91dfa572490044c317194c45d03f5653dfd4de90

Kinda works, got a massive issue in that all gets are returning null. Not sure why :cry:

**Comment by lol768** [comment]
Fixed.
