### ISSUE TITLE
KillCommand glitch?

### ISSUE THREAD

**Issue by memoriessadnessregret** [np98765/BattleKits#100]
Hey there,

I wanted to set it up so that whenever a player killed another player, they are rewarded for $100. So, under the killcommand section I put in the command
- eco give player 100

This works perfectly fine but whenever a player kills themselves, they are rewarded with the $100 as well. Is it possible to make it so that these commands are only executed when a player kills ANOTHER player, not him or herself? Thanks in advance.

**Comment by lol768** [comment]
The above commits should fix this. I'll be hopefully pushing this out for v2.0.3 on BukkitDev soon (probably after v2.0.2) is approved.
