### ISSUE TITLE
One kit is constantly erroring!

### ISSUE THREAD

**Issue by adammesa** [np98765/BattleKits#104]
Hello, not too sure why but one of our kits are constantly erroring (no matter what I do), using a sign, /bk or /kit does not make a difference...
I have a few plugins working along side Battlekits, the main one that's being used there is RPG Items and AncientRPG - I have these working on other kits which do work fine without erroring. Not too sure what I did wrong

I was wondering if you could help:

_Here is the kit configuration:_

<pre>
  Ender:
    active-in: '''Badlands'''
    on-give-message: '&7Class changed to &6Ender&7!'
    xpLevels: 0
    tagPrefix: '&a'
    commands:
#    - sudo <player> race set Elemental
    - class set <player> ender
    - rpgitem ender1 give <player>
#    - sudo <player> updateinv
    items:
      helmet: iron
      chestplate: leather
      leggings: leather
      boots: iron
      bootsEnchant: 2:5
      '0': '0'
      '1': '267'
      '2': '320:64'
      '3': '261'
      '4': '262:64'
      '5': '262:64'
      '6': '0'
      '7': '0'
      '8': '0'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
</pre>

_Here is the error in the console, sorry if I was supposed to paste it somewhere else:_

<pre>
03.03 12:33:18 [Multicraft] Skipped 3 lines due to rate limit (30/s)
03.03 12:33:14 [Server] INFO at com.lavacraftserver.BattleKits.CommandBattleKits.supplyKit(CommandBattleKits.java:545)
03.03 12:33:14 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:421)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:489)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:228)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:600)
03.03 12:33:14 [Server] INFO at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:66)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
03.03 12:33:14 [Server] INFO at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:174)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:853)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.java:909)
03.03 12:33:14 [Server] INFO at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerConnection.java:993)
03.03 12:33:14 [Server] INFO at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:536)
03.03 12:33:14 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
03.03 12:33:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
03.03 12:33:14 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:299)
03.03 12:33:14 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:314)
03.03 12:33:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
03.03 12:33:14 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'kit' in plugin BattleKits v2.0.3
03.03 12:33:14 [Server] SEVERE Unhandled exception executing command 'kit' in plugin BattleKits v2.0.3
</pre>

**Comment by lol768** [comment]
Looks like it doesn't like the kit commands. Try removing the commands block and see if the error persists.

**Comment by lol768** [comment]
Wrap the commands in single quotes.....
