### ISSUE TITLE
Won't Start Up (Unable to load plugin)

### ISSUE THREAD

**Issue by narwhale12345** [np98765/BattleKits#106]
Here is the error: http://pastebin.com/jp9gEN9Q

[Edit] I was reading up on other issues and updated my java to Version 7 Update 17 but it still won't work here is the error: http://pastebin.com/u2jWPZ2k

**Comment by simosha** [comment]
I have a few questions. How do I remove all my inventory when I warp with commands and signs. How do I remove all potion effects from the player when a new kit is selected?

**Comment by lol768** [comment]
"[Edit] I was reading up on other issues and updated my java to Version 7 Update 17 but it still won't work here is the error: http://pastebin.com/u2jWPZ2k"

You're still running Java <7 if you see this error. Update.

"How do I remove all my inventory when I warp with commands and signs. How do I remove all potion effects from the player when a new kit is selected?" Outside scope of plugin - see the vanilla effect command and clear command.
