### ISSUE TITLE
Restrictions. Not working

### ISSUE THREAD

**Issue by lukeyc** [np98765/BattleKits#109]
Hello, I am very confused on how the restriction system operates.
I am currently using the latest version of craftbukkit and battlekits.
What I am trying to do:

Have it to where when you have a kit you cannot drop items / drop items when you die.

I am very confused because when enable Restrictions the players that aren't using a kit cannot build. So I then added BattleKits.bypassRestriction.\* to the group in permissionsex and reloaded the server. This still wouldn't let me build when im not in a kit, but when I use a kit it lets me build fine.

Im not really sure what I am doing wronge, I just reccommend you change the Restrictions system. Otherwise, I think this Plugin is one of the best plugins out there :)

**Comment by lol768** [comment]
We don't support PEX, sorry.

**Comment by lukeyc** [comment]
Ok, I just want to let you know that using permissions is kinda confusing and recommend that you should have a different method of applying restrictions to players, Thanks.

**Comment by lol768** [comment]
Sure, it's something I'll definitely look into

**Comment by 3dbullet** [comment]
You should make it like the it was before where you can enable and disable it in the battlekits config because im having the same problem with me not being able to get player drops working or players not picking up items please tell me if you have got a fix and btw i use essentials groupmanager
