### ISSUE TITLE
Latest Craftbukkit, latest battlekits version = could not load 

### ISSUE THREAD

**Issue by Askotion** [np98765/BattleKits#114]
Hello,
I have a problem with battlekits.
I downloaded the jar on bukkit.org and put it into the 
Pluginsfolder. Then I restart my server but nothing changed. There is nowhere a folder and nothing about bk in the log ;(
I hope you can help me :)

**Comment by Askotion** [comment]
Edit: now it told me "could not load"
Here is my log:
http://pastebin.com/7y4QQzSE

**Comment by np98765** [comment]
You will need to update to Java 7.
