### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by RSev** [np98765/BattleKits#116]
i read the page on how to make the config work i did bk reload it reloaded but the effects did not take place when i tried to use a new kit
config:
http://pastebin.com/RnWse9ik
 i tried to add 2 more kits but it didn't work
so anyhelp would be appreciated

**Comment by lol768** [comment]
Wrap enchantments in single quotes
L21,L22,L38,L39,L67,L110,L111,L126,L127,L169,L170,L196,L197,L198,L199,L200,L216,L217 all need to be fixed in this manner.
