### ISSUE TITLE
Auto-acquiring kits and chance to get an item

### ISSUE THREAD

**Issue by ghost** [np98765/BattleKits#117]
Could you make a permissions for auto acquiring a kit? So when somebody enters the server for the first time he gets the kit and with "BattleKits.auto.*" will get it all the time?
So there won't be a need for signs and commands.

And it would be nice to have a 'chance' option to every slot so once in a while instead of a iron pickaxe a player would get a diamond one, like

'0': '270 40%, 274 30%, 257 20%, 278 10%'

**Comment by np98765** [comment]
You will need to use another plugin for auto-equipping kits on player logins.  There are numerous plugins that can achieve this (if you use Skript, I'm sure you can accomplish this).

The chance idea sounds interesting, but I'm not sure how feasible it would be, especially if we have to change the config layout and complicate things further.

Adding it to the potential to-do list and closing this for now.
