### ISSUE TITLE
How to combine the pluggin with Survival Games one.

### ISSUE THREAD

**Issue by MrDiao10** [np98765/BattleKits#118]
I am trying to use BattleKits with Survival Games pluggin, but the problem is SG pluggin doesn´t "kill" the players, it just send the players to the lobby when they lose all their life. But it doesn´t counts as a kill.
Is there any option to set BattleKits useful with Survival Games pluggin?

**Comment by np98765** [comment]
Hi there,

Unfortunately, there is nothing we can do about this.  You will have to discuss this issue with the author of SurvivalGames, as we cannot detect when a player dies if they never die.

Closing this report for now; you can re-open it you learn any new information that might help us achieve compatibility with SurvivalGames.
