### ISSUE TITLE
Chain armor doesn't apply to kits

### ISSUE THREAD

**Issue by madminer12** [np98765/BattleKits#119]
helmet: chain
      chestplate: chain
      leggings: chain
      boots: chain

NOPE, IT DOESN'T WORK

(I didn't put the whole code on purpose)

**Comment by np98765** [comment]
Hi there,

The correct variable is "chainmail", not "chain". :)

**Comment by Mrlong2** [comment]
PUT THIS ON The bukkit page!!!

**Comment by Mrlong2** [comment]
it took me, five hours to find this!
