### ISSUE TITLE
Giving potions in kits are not working.

### ISSUE THREAD

**Issue by MapleFighter** [np98765/BattleKits#12]
I believe, after testing to add potions in kits, that potions are not actually working. Probably because potions go in the 373:(potionvalue) format and for BattleKits, ItemID:(Amount) is implemented. I know potioncommands is a solution but I want to use health potions which cannot be given as an effect. Thanks guys.

**Comment by lol768** [comment]
Pretty sure this issue is invalid. I'll check the code but I'm 99% sure we do support data values attached to items.

**Comment by lol768** [comment]
Yep, we do indeed support this:
https://github.com/np98765/BattleKits/blob/master/BattleKits/src/com/lavacraftserver/BattleKits/CommandBattleKits.java#L199

Gonna close this issue. Comment if you want some help on doing this in your config file.
