### ISSUE TITLE
Battle Kits Sign Problem

### ISSUE THREAD

**Issue by Bar108** [np98765/BattleKits#121]
Thats the bug:
http://www.youtube.com/watch?v=gs9CJ5otHd0
Can you please fix it?
ppl in my server glitching with it

**Comment by lol768** [comment]
We're aware of this, however I'm not sure what causes it.

**Comment by lol768** [comment]
Can you reproduce this with LiteKits?

**Comment by Bar108** [comment]
You mean I should remove the BattleKits and install instead LiteKits or what?

**Comment by lol768** [comment]
I'm curious as to whether LiteKIts has the same problem when you switch between kits - it's not a replacement for BattleKits (yet) and it won't support signs but I just want to know if two kits will have the same issue with LiteKits.

**Comment by Bar108** [comment]
But LikeKits is not supporting signs so it doesnt matter
BTW
ive found a server where that bug is not existing
His IP  is 46.117.176.176
Can you please check why itslike that
And what the best solution you are recommending me to do?

**Comment by lol768** [comment]
Try using server signs and binding the kit command to a sign.

**Comment by Bar108** [comment]
But in the server ive sent you it seema that the BattleKits plugin working fine without the bug.
Then how can you explain it?

**Comment by adammesa** [comment]
I've also had the same problem as you, Bar108... have you tried reconnecting when that glitch occurs, and seeing if the sword is still in your inventory? (Sometimes it fails to properly update your own inventory :( 
:+1:

**Comment by Bar108** [comment]
I am using now ServerSigns and it works great :D
You can close :D
