### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Croeder77** [np98765/BattleKits#122]
Hello, I have been having a problem with BattleKits recently. Every time I do a command by battlekits, it says:

An internal error occurred while attempting to form this command

I know the problem, well a little part of it. Whenever I reset my kit config, everything works fine. So I know I did something wrong with my kit config.

Here is my kit config: http://pastebin.com/kF19ecsR

Does anybody know how to fix this?

**Comment by np98765** [comment]
Just from taking a quick glance at your config, I noticed that you haven't wrapped slot 0 in the archer kit and the knight kit in single quotes.

Change that and re-test, then let me know your results!

**Comment by lol768** [comment]
Not following #1

**Comment by Croeder77** [comment]
np98765, I have fixed the issue that you noticed, and completely restarted the server. It appears that there is still an internal error when I try performing the commands. I will continue my search for the problem.

**Comment by lol768** [comment]
What's the new error in the console?

**Comment by Croeder77** [comment]
org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
14.05 14:38:50 [Server] INFO at com.lavacraftserver.BattleKits.CommandBattleKits.onCommand(CommandBattleKits.java:52)
14.05 14:38:50 [Server] INFO Caused by: java.lang.NullPointerException
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
14.05 14:38:50 [Server] INFO at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)

^^
Those are some errors & stuff in the console that I found when trying the command /bk, /kits, etc.

**Comment by lol768** [comment]
**You cannot do this:**
![Issue](http://lol768.com/screenshots/20130515193000.png)
(Use double quotes for the outside, and signle or the inside.)

![Issue](http://lol768.com/screenshots/20130515193250.png)
(The right-hand-side must be wrapped in single quotes)

![Issue](http://lol768.com/screenshots/20130515193328.png)
(Same problem)

**Potential issues:**
Ideally all text should be wrapped in single quotes, e.g. 
![Potential issue](http://lol768.com/screenshots/20130515193409.png)

Should be:
![Fixed](http://lol768.com/screenshots/20130515193447.png)

**Once you think you've fixed these issues, use [this tool](http://yaml-online-parser.appspot.com/) to check your config file (just paste it in).**

**Comment by Croeder77** [comment]
Alright, thank you guys SO much! I have fixed it, and I found another problem that wasn't detected:

When I named the bow in the archer kit as: '&cArcher's Bow', I realized that I couldn't have the ', because it ruins the coding, and thinks you're trying to do something else, other than naming something.

**Comment by lol768** [comment]
Good catch, yeah. You'll need to escape single quotes with a backslash,

'Archer\'s Bow'

**Comment by lol768** [comment]
Seems all sorted.
