### ISSUE TITLE
Active in issue

### ISSUE THREAD

**Issue by Ccap67** [np98765/BattleKits#125]
CraftBukkit version: 1.5.2-R0.1
Plugin list: 16:19:06 [PlugMan, WorldEdit, Vault, Multiverse-Core, Permis
sionsEx, WorldGuard, WGRegionEvents, ProtectionStones, PotionCommands, SurvivalG
ames, InstaSoup, cShortcut, ZavAutoMessager, Lockette, Modifyworld, ProtocolLib,
 Herochat, WGCustomFlags, Essentials, BattleKits, WGPlayerDamageFlags, Essential
sProtect, WGFlyFlag, ServerSigns, EssentialsSpawn, Multiverse-Inventories, WGDro
pFlags, WGRegionCommands, WGRegionEffects, EssentialsChat
BattleKits version: Latest
Config file link (pastebin.com): http://pastebin.com/Eiwm6TAr
Server log link (pastebin.com): There is no error so there is no reason for the server log

When does the error occur?: It is not an error. It is a bug. When I type in the correct node for the plugin to only be used in a certain world, it still lets people use it in all worlds.

Steps to reproduce error: I do not know how to fix this.

**Comment by Goblom** [comment]
Next time give everything you can please.

When you are talking about node i am assuming you are talking a permission node, if so please post your permissions.yml file from PermissionsEx.

Also need to see your global.yml file from BattleKits, and the world you are trying to use the kit in.

**Comment by lol768** [comment]
Only give them the use permission in the worlds you want them to be able to use kits in.
