### ISSUE TITLE
Internal Error and Unable to give kits

### ISSUE THREAD

**Issue by NGOXL1** [np98765/BattleKits#129]
Hello there Authors and Contributors to the BattleKits plugin,

I am having the same issue as Will0akTree, where some kits will not give me all the items. I have PM'd np98765 on BukkitDev, and he referred me here will one tip, to wrap the '0': slot in single quotes, but this seemed not to work.

Here is a PasteBin of my kits.yml: http://pastebin.com/47MjWDjV

I must say that the only kits that have been broken are Berserker, Standard and Scout. The ones without the quotes around slot 0 are the ones that are working properly, strangely. I have found that it is some sort of armour/armor error with the standard kit, but the other 2 I have no ideas for.

This does not have to be a very soon reply, but as quick as you'd find still feasible would be lovely.

Cheers!
- NGOXL1

**Comment by lol768** [comment]
Wrap enchantments in single quotes.......

**Comment by NGOXL1** [comment]
I have done that, but it doesn't work!

**Comment by NGOXL1** [comment]
Ohh! Enchantments only! That's the problem. Thanks a bunch!

**Comment by lol768** [comment]
Glad it's sorted :smile:
