### ISSUE TITLE
Coding Issue

### ISSUE THREAD

**Issue by yoyoawesome** [np98765/BattleKits#132]
I'm pretty sure that I'm following all of the coding correctly, but every time I change something it gives me an internal error. Please help. Here is my config:

kits:
  Warrior:
    active-in: all
    on-give-message: '&b&lYou are now a &6&lWarrior'
    cost: 0
    xpLevels: 0
    tagPrefix: '&a'
    commands:
    items:
      helmet: iron
      chestplate: iron
      leggings: iron
      boots: iron
      '0': '267'
      '1': 261 51:1
      '2': '0'
      '3': '0'
      '4': '0'
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '0'
      '9': '262'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
      names:
        '0': '&a&lHero\'s Sword'
        '1': '&a&lHero\'s Bow'
  SwordsMan:
    active-in: all
    on-give-message: '&b&lYou are now a &6&lSwords Man'
    cost: 0
    xpLevels: 0
    tagPrefix: '&a'
    commands:
    items:
      helmet: leather
      chestplate: iron
      leggings: iron
      boots: leather
      helmetColor: '#999999'
      bootsColor: '#999999'
      '0': 267 16:1
      '1': '0'
      '2': '0'
      '3': '0'
      '4': '0'
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '0'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
      names:
        '0': '&a&lHero\'s Sword'
  Fighter:
    active-in: all
    on-give-message: '&b&lYou are now a &6&lFighter'
    cost: 0
    xpLevels: 0
    tagPrefix: '&a'
    commands:
    items:
      helmet: leather
      chestplate: leather
      leggings: leather
      boots: leather
      helmetColor: '#999999'
      chestplateColor: '#999999'
      leggingsColor: '#999999'
      bootsColor: '#999999'
      '0': 267 16:1
      '1': 261 51:1 48:1
      '2': '0'
      '3': '0'
      '4': '0'
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '0'
      '9': '262'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
      names:
        '0': '&a&lHero\'s Sword'
        '1': '&a&lHero\'s Bow'
  Sniper:
    active-in: all
    on-give-message: '&b&lYou are now a &6&lSniper'
    cost: 0
    xpLevels: 0
    tagPrefix: '&a'
    commands:
    items:
      helmet: iron
      chestplate: leather
      leggings: leather
      boots: iron
      chestplateColor: '#999999'
      leggingsColor: '#999999'
      '0': 261 51:1 48:1
      '1': '0'
      '2': '0'
      '3': '0'
      '4': '0'
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '0'
      '9': '262'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
      names:
        '0': '&a&lHero\'s Bow'
Pretend that the spaces are all there I know that those are correct because I just copy and paste.

**Comment by lol768** [comment]
Please wrap all item info (enchantments) in 'single quotes' (like that).

E.g.
`'0': '261 51:1 48:1'`

Next time you report an issue:
- Follow #1
- Use pastebin to generate a link to the config
