### ISSUE TITLE
Players can't access or use BattleKits signs and commands.

### ISSUE THREAD

**Issue by FlintGoblin** [np98765/BattleKits#135]
- Players can't access or use the commands /bk,/battlekits/kits command, They can't also access [BattleKits] signs.
- Whenever they click the signs or use commands this appears:
  ![4](https://f.cloud.github.com/assets/4650661/628313/2107d640-d098-11e2-8ac8-0f494d87549e.png)
- As a server OP I can access the commands and signs which means that the plugin is 
  properly working. ![1](https://f.cloud.github.com/assets/4650661/628317/696b9778-d098-11e2-8008-c3721409e181.png)

<b>This is my global.yml format</b>
 ![6](https://f.cloud.github.com/assets/4650661/628323/a9ac3ada-d099-11e2-8773-8cc10c9c0023.png)
# How can players access the BattleKits commands and signs?

**Comment by FlintGoblin** [comment]
Bump

**Comment by FlintGoblin** [comment]
Bump

**Comment by FlintGoblin** [comment]
Bump

**Comment by FlintGoblin** [comment]
Bump

**Comment by lol768** [comment]
I know, let's bump the issue 3 times in one minute! That's gonna get you faster support.
