### ISSUE TITLE
Kits Not Pemanent

### ISSUE THREAD

**Issue by DezBax512** [np98765/BattleKits#139]
I have a problem with kits that cost money i dont really know how to make them permanent once players buy them so they dont have to keep buying because its beginning to become a real issue on my server people are getting upset because they wasted their money for no reason Please respond

**Comment by lol768** [comment]
Stop them dropping stuff on death?

**Comment by DezBax512** [comment]
no like when they respawn it charges them again and it doesnt save it when they buy the kits so i need to find a way that they can change kits without having to rebuy the kit they already have

**Comment by DezBax512** [comment]
basicly when they buy kits they cant change it and if they do change it they are going to have to rebuy the kit

**Comment by lol768** [comment]
Outside of plugin scope.
