### ISSUE TITLE
Once per life error

### ISSUE THREAD

**Issue by rnoa** [np98765/BattleKits#142]
OP on my server have an issue with kits. When we die it says "You may now use a kit", then immediately after "Please chose a valid kit" and when we click on the kit sign it says "You may only use one kit per life" so there is no way we can get a kit. Some time ago we got kits auto until I removed that permission by giving a negative permission node on respawning with autokits and it worked fine, but now this is happening. No error on the console, it says the kit I am chosing is being supplied. Please help!
Craftbukkit version rb 2788 (the latest recommended build)
BattleKits version 2.0.3
Plugins: essentials, battleArena with all its addons: arenaspleef, arenapaintball, arenactf, arenafutbol, arenaparkour, battletracker, citizens, chestshop,TagApi Thehungergames, ultimate skyblock, WE, WG, lottery, GroupManager, TimTheEnchaner, Iconomy, SimpleRegionMarket, mobarena, crackshot.

**Comment by lol768** [comment]
User error: permissions
