### ISSUE TITLE
Re-Naming Armour

### ISSUE THREAD

**Issue by HardcorePark** [np98765/BattleKits#146]
Hey, So basically, I'm trying to rename armour, but the armour in:

Items:
  helmet: iron
  helmetEnchant: 0:1

I'm wondering if its possible to rename the auto-equip armour, or do i have to place it in a invetnroy slot, and make players manually equip the armour, if not. Could this be inplamented in next version? Thanks.

HardcorePark

**Comment by lol768** [comment]
Will be possible with new ItemStack serialization code
