### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by XniphicG** [np98765/BattleKits#15]
Um im a bit new to plugins and stuff, but every time i edit the config (try to add a kit) it doesnt add it at all it just restarts my config please, or make a tutorial on how to make a kit please :)

**Comment by lol768** [comment]
Firstly, please read the guidelines: https://github.com/np98765/BattleKits/issues/1

Secondly, you failed to read the FAQ on the BukkitDev page.

To answer your question, /bk reload
