### ISSUE TITLE
Kits Auto Given on Respawn when not set.

### ISSUE THREAD

**Issue by Sup3rBlaze** [np98765/BattleKits#167]
Hello,
When ever I kill myself, it automatically gives me a kit. The kit name is Default, I don't know if that would have a problem with it, but I don't know why I am getting the kit when there are no perms set to do that? please help me.

**Comment by drtshock** [comment]
Can you post your configs please? :)

**Comment by Sup3rBlaze** [comment]
Kits Config: http://pastebin.com/wnixjwU7
KitHistory Config: http://pastebin.com/3Bva96dV
Global Config: http://pastebin.com/8ig1zASb

I am also an OP if you need to know that.

**Comment by lol768** [comment]
You must negate the appropriate node.
