### ISSUE TITLE
My BattleKits problems.

### ISSUE THREAD

**Issue by FirecatHD** [np98765/BattleKits#169]
Hi i am having some problems with the global.yml file.

Link: http://pastebin.com/4sHSpxpm

I want it to be like this:

Instant soup: yes
Heals what: hearts
No dropping items or item dropping on death.
No loosing hunger.

This is my problems i think (I will throw in some more if there is)

Also is it possible to toogle this for worlds because i only want the mentioned to be active in one world.
And is the fact that KFactions is installed a problem, and is there a way to disable KFactions in the KitPvP world? (i know i should problably ask the outhors of kfactions but maybe someone here knows a way?)

So if someone could edit this yml file for me and tell me what i did wrong, i would be very grateful !

How do i select an area for PvP? sry noob Q :/

Thanks :)

**Comment by lol768** [comment]
This is not a bug or feature request.
