### ISSUE TITLE
permission problems

### ISSUE THREAD

**Issue by iambeast43** [np98765/BattleKits#179]
why can defaults use the overlord kit but not pyro+

Default:
    default: true
    permissions:
    - -bukkit.command.kill
    - battlekits.use.heavy
    - battlekits.use.pyro
    - battlekits.use.archer
    - battlekits.listkits
    - battlekits.sign.use
    inheritance:
    - g:groupmanager_default
    - g:bukkit_default
    - g:essentials_default
    - g:towny_default
    info:
      prefix: '&7'
      build: true
      suffix: ''
  Builder:
    default: false
    permissions:
    - battlekits.use.heavy
    - battlekits.use.pyro
    - battlekits.use.archer
    - battlekits.listkits
    - battlekits.sign.use
    inheritance:
    - default
    - g:essentials_builder
    - g:towny_builder
    info:
      prefix: '&2'
      build: true
      suffix: ''
  Moderator:
    default: false
    permissions:
    - battlekits.use.heavy
    - battlekits.use.pyro
    - battlekits.use.pyro+
    - battlekits.use.archer
    - battlekits.listkits
    - battlekits.sign.use
    inheritance:
    - builder
    - g:groupmanager_moderator
    - g:bukkit_moderator
    - g:essentials_moderator
    - g:towny_moderator
    - g:vanish_moderator
    info:
      prefix: '&5'
      build: true
      suffix: ''
  Admin:
    default: false
    permissions:
    - battlekits.use.overlord
    - battlekits.use.heavy
    - battlekits.use.pyro
    - battlekits.use.pyro+
    - battlekits.use.archer
    - battlekits.listkits
    - battlekits.sign.use
    inheritance:
    - g:groupmanager_admin
    - g:bukkit_admin
    - g:essentials_admin
    - g:towny_admin
    - g:vanish_admin
    info:
      prefix: '&2[&dAdmin&2]&b'
      build: true
      suffix: ''
  Owner:
    default: false
    permissions:
    - '_'
    - -vanish._
    inheritance:
    - admin
    info:
      prefix: ''
      build: true
      suffix: ''

**Comment by Maximo-TP** [comment]
Hi,
Even when I give permission, shows the message: You do not have permission to use this kit.
What can I do?

**Comment by lol768** [comment]
Follow #1 please.

**Comment by FowenX** [comment]
This ticket isn't closed, so help? There is NOTHING else wrong with the plugin except for the fact that when users right click the sign, it says "User doesn't have permission".

I am using GroupManager, and gave the groups these possible nodes:
    - BattleKits.use.archer
    - BattleKits.use.Archer
    - BattleKits.sign.use
    - BattleKits.kit.Archer
    - BattleKits.kit.archer

I tried Uppercase and Lowercase, and they still won't work, thanks!

**Comment by lol768** [comment]
battlekits.sign.use and battlekits.use.kitname are the only permissions they should need. "User doesn't have permission." isn't an error BattleKits gives. BattleKits would send a "You don't have permission to use kit signs" error or a "You do not have permission to use this kit!" error.
