### ISSUE TITLE
Internal error when I do /kits

### ISSUE THREAD

**Issue by fuzzyhusky** [np98765/BattleKits#181]
Idk whats wrong, heres the only thing I found in my console regarding BattleKits
: http://pastebin.com/veZAMg5m

heres my kits.yml: http://pastebin.com/5PdyU693

the issue started when i added the kit donor. please help, btw i looked at #122 but nothing seemed to help. i tried everything and yea.

**Comment by lol768** [comment]
`'0': 261 49:2` needs quotes around it because it uses the ':' character. Should look like `'0': '261 49:2'`. This will be the case for a lot of lines in the file. https://github.com/np98765/BattleKits/blob/master/src/main/resources/kits.yml has a working config you can use.
