### ISSUE TITLE
BattleKits 'An internal error'

### ISSUE THREAD

**Issue by Oarbs** [np98765/BattleKits#189]
Most of my kits have been working fine when I used them, but I have recently made two kits that are not working properly. Whenever I do /kit [kitname], I get the kit but I get the error ingame that says: 'An internal error occurred while attempting to perform this command'. I listed the text below, the kits that are not working properly are Witch and Blaze. Sorry if I'm missing something obvious, I'm new to this plugin. Thanks for your help and time!

kits:
  archer:
    active-in: '''PvP'''
    items:
      helmet: gold
      chestplate: diamond
      leggings: diamond
      boots: diamond
      '0': 350:64
      '1': '0'
      '2': '0'
      '3': '0'
      '4': 261 48:3
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '332:16'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': 262:64
      '17': 262:64
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
  pvp:
    active-in: '''PvP'''
    items:
      helmet: diamond
      chestplate: iron
      leggings: iron
      boots: diamond
      '0': 350:64
      '1': '0'
      '2': '0'
      '3': '0'
      '4': 276 16:1
      '5': '0'
      '6': '0'
      '7': '0'
      '8': '332:16'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
  russia:
    active-in: '''PvP'''
    items:
      helmet: gold
      chestplate: iron
      leggings: gold
      boots: gold
      '0': '350:64'
      '1': '0'
      '2': '0'
      '3': 272 19:2
      '4': 272 16:5 
      '5': 272 20:1
      '6': '0'
      '7': '0'
      '8': '332:16'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '0'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
  Blaze:
    active-in: '''PvP'''
    items:
      helmet:
      chestplate: gold
      leggings:
      boots:
      chestplateEnchant: 1:3
      '0': '350:64'
      '1': '0'
      '2': '0'
      '3': 261 50:1 48:1
      '4': '0'
      '5': 283 20:2 34:3 16:1
      '6': '0'
      '7': '0'
      '8': '332:16'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': '262:64'
      '17': '262:64'
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
  Witch:
    active-in: '''PvP'''
    items:
      helmet: iron
      chestplate: gold
      leggins: gold
      boots: iron
      chestplateEnchant: 1:3
      '0': '373:1:16147'
      '1': '0'
      '2': '373:1:16386'
      '3': '0'
      '4': 268 16:3
      '5': '0'
      '6': '373:1:16426'
      '7': '0'
      '8': '373:1:16460'
      '9': '0'
      '10': '0'
      '11': '0'
      '12': '0'
      '13': '0'
      '14': '0'
      '15': '0'
      '16': 262:64
      '17': 262:64
      '18': '0'
      '19': '0'
      '20': '0'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'

**Comment by KartikChugh** [comment]
Internal errors are normally caused by YAML issues. It would be easier to help if you put the kits.yml into http://yaml-online-parser.appspot.com/  clicked on "Link to this page", and then gave the url

**Comment by lol768** [comment]
`'0': 350:64` needs quotes around it because it uses the ':' character. Should look like  `'0': '350:64'`. This will be the case for a lot of lines in the file. https://github.com/np98765/BattleKits/blob/master/src/main/resources/kits.yml has a working config you can use.
