### ISSUE TITLE
NBT DATA

### ISSUE THREAD

**Issue by KartikChugh** [np98765/BattleKits#190]
Is it possible to add NBT Tags onto an item, from the kits.yml?

**Comment by lol768** [comment]
Nope, sorry.

**Comment by KartikChugh** [comment]
Lol you came back??

**Comment by lol768** [comment]
Just cleaning up a few tickets - no plans to work on this plugin.

**Comment by KartikChugh** [comment]
Haha ok.
I asked you on PM about NBT a year ago, you said to find another developer to add it
