### ISSUE TITLE
Killstreaks

### ISSUE THREAD

**Issue by terakasel** [np98765/BattleKits#191]
My killstreaks aren't working.  They are enabled and everything but won't show ingame.  Thoughts?

**Comment by terakasel** [comment]
Am I going to get any help for this?

**Comment by terakasel** [comment]
Shitty service is shitty.

**Comment by Lolmewn** [comment]
Were sorry, non shitty service is only available for 10€/m (discounted rate)! In the mean time, please enjoy all other features of the plugin while someone who actually did work on the plugin might respond.

**Comment by lol768** [comment]
`
Am I going to get any help for this?
`

No. (This plugin isn't maintained anymore)
