### ISSUE TITLE
Internal error when using /kit

### ISSUE THREAD

**Issue by MyBiddyBunnys** [np98765/BattleKits#194]
Alright, I know I did something wrong in the config. Just can't find it! Here is the pastebin http://pastebin.com/3PF6CsCu Please help me find the error.

-Biddy

**Comment by lol768** [comment]
`bootsEnchant: 2:1 3:5` needs quotes around it because it uses the ':' character. Should look like `bootsEnchant: '2:1 3:5'`. This will be the case for a lot of lines in the file. https://github.com/np98765/BattleKits/blob/master/src/main/resources/kits.yml has a working config you can use.
