### ISSUE TITLE
Error in console on startup

### ISSUE THREAD

**Issue by ghost** [np98765/BattleKits#197]
I am getting a strange error in the console when I start my server:
http://pastebin.com/dDiqCgqN
I have over 70 plugins so a incompatibility issue definitely is possible.

**Comment by CeramicTitan** [comment]
Run the plugin on a blank test server and tell me if the problem persists.

**Comment by ghost** [comment]
I do not have this problem when I run it on a blank server. Also if this error occurs on startup I cannot use any of the commands because whenever I try to do /kit for example it simply tells me how I should use the command:
/kit [kit] [player]
/kit [kit]

**Comment by ghost** [comment]
Anyone have a solution?

**Comment by lol768** [comment]
This is an issue with the auto-updater (and Curse generating incorrect RSS markup). I'd suggest just disabling the auto-updater to be honest. This plugin isn't going to be updated any time soon.
