### ISSUE TITLE
BattleKits "an internal error occured while attempting to perform this command"

### ISSUE THREAD

**Issue by SuperBoy1097** [np98765/BattleKits#200]
I am using spigot and I edited the config for custom kits and such, and when i use the kit it says the command "an internal error occured while attempting to perform this command"
here is the config kits http://pastebin.com/nJdYXEdJ

**Comment by lol768** [comment]
Line 23:

`bootsEnchant: 2:1 3:5` is invalid and should be `bootsEnchant: "2:1 3:5"`

**Comment by SuperBoy1097** [comment]
still doesnt work

**Comment by lol768** [comment]
Line 69 has the same problem:

`'0': 276 16:1` should be `'0': '276 16:1'`.

Line 7,8 and 9 have no value and should be removed. I suggest you read the [spec](http://yaml.org/spec/).
