### ISSUE TITLE
Server kits Errors!

### ISSUE THREAD

**Issue by EulersPie** [np98765/BattleKits#202]
Hi, How Come When I Setup A kit and I Assigned It To A Sign It Would Only Load The Specific Item In The Slot, The Rest Are Invisible Until You Switch Slots, but Sometimes I Don't Even Get The kit Itself
.

**Comment by yuuuup** [comment]
Me too

**Comment by lol768** [comment]
This is unlikely to be fixed.

**Comment by LaxWasHere** [comment]
omg hiii lol768.

**Comment by lol768** [comment]
Hi @LaxWasHere :smile:

**Comment by yuuuup** [comment]
I fixed it

I just messed up the kits yaml. LOL.
