### ISSUE TITLE
internal error well trying to to use a custom kit

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [np98765/BattleKits#204]
# Kit definitions
# This is where you can add your own kits and customise various details

kits:
  starterpack:
    active-in: '''HUB'',''survival2pve'',''survival1pve'',''survival1pvp'',''survival2pvp'',''word_nether'',''word_end'''
    on-give-message: '&cEnjoy your kit!'
    cost: 
    xpLevels: 
    tagPrefix: 
    commands:
    - tell <player> Enjoy your kit :)
    items:
      helmet: Chainmail
      chestplate: Chainmail
      leggings: Chainmail
      boots: Chainmail
      helmetDurability: 
      helmetColor: 
      chestplateColor: 
      leggingColor: 
      bootColor: 
      bootsEnchant: 2:1 3:5
      '0': '272 :19'
      '1': '274 :32'
      '2': '273 :32'
      '3': '275 :32'
      '4': '322'
      '5': '322'
      '6': '322'
      '7': '322'
      '8': '322'
      '9': '322'
      '10': '50'
      '11': '50'
      '12': '50'
      '13': '50'
      '14': '50'
      '15': '50'
      '16': '50'
      '17': '50'
      '18': '50'
      '19': '50'
      '20': '58'
      '21': '0'
      '22': '0'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '0'
      '29': '0'
      '30': '0'
      '31': '0'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'

**Comment by lol768** [comment]
Invalid YAML (this is not a plugin issue!), use quotes around values with colons (e.g. `bootsEnchant: 2:1 3:5` should be `bootsEnchant: "2:1 3:5"`).

**Comment by REVIEWGAMINGMAN** [comment]
i'm still getting error

**Comment by REVIEWGAMINGMAN** [comment]
I need suggestions

**Comment by lol768** [comment]
There are multiple of these issues in the config file. Paste your config into http://yaml-online-parser.appspot.com/ and watch as the parser fails to parse it
