### ISSUE TITLE
Permission Problem

### ISSUE THREAD

**Issue by craftingTARDIS50** [np98765/BattleKits#205]
So, I'm trying to do KitPvP on my server, but only OP's can do kits. I see answers to posts saying to "use permission "example.battlekits.blah" but I have no idea how you implement that..
So can you please tell me how to use permissions to have non-op's get kits? Thank you.
That's all I need.

**Comment by lol768** [comment]
At this point, the plugin and is so old and unmaintained I'd be surprised if it works at all. The API the plugin relies on is also very much dead.

But in general terms:
- You need a permissions plugin. Something like bpermissions, GroupManager, PermissionsBukkit, Privileges, PEX etc.
- You need to grant the use permission to everyone in the default group. Consult the permission plugin's documentation for information on how to do this.

**Comment by craftingTARDIS50** [comment]
Thanks!
