### ISSUE TITLE
Kits being given automatically from dotcurrency

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#23]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=326 (author: dotcurrency) at Dec 12, 2012 at 01:15 UTC**

When my players respawn they automatically get the kit in the top of my kits.yml
How do I disable this? I can't seem to find the option in the config.

**Comment by lol768** [comment]
Make sure players **do not** have the permision `BattleKits.auto.kitName`. You can also completely turn off this functionality by setting `override-disable-respawn-kits` to true in your global.yml file.

**Comment by dotcurrency** [comment]
OK thanks it works now
