### ISSUE TITLE
Any reason why I can't use Potions in kits?

### ISSUE THREAD

**Issue by KylexDavis** [np98765/BattleKits#26]
Here is my config for a kit that I want to be called "wizard" everything is working apart from the potions, they are just giving me stacks of water bottles. Any reason for this? Thanks in advance.

![thispicture](https://f.cloud.github.com/assets/3027729/8912/6f7749d8-448d-11e2-9fde-01397a86ab54.png)

 wizard:
    active-in: all
    commands:
    - potion <player> speed 36000
    - potion <player> fireresistance 24000
    items:
      helmet: gold 
      chestplate: gold
      leggings: gold
      boots: gold
      '0': 280 16:5 19:2 
      '1': '373:16428'
      '2': '373:16388'
      '3': '373:16392'
      '4': '373:16394'
      '5': '282'
      '6': '282'
      '7': '282'
      '8': '282'
      '9': '0'
      '10': '373:16428'
      '11': '373:16388'
      '12': '373:16392'
      '13': '373:16394'
      '14': '0'
      '15': '0'
      '16': '0'
      '17': '262'
      '18': '0'
      '19': '373:16428'
      '20': '373:16388'
      '21': '373:16392'
      '22': '373:16394'
      '23': '0'
      '24': '0'
      '25': '0'
      '26': '0'
      '27': '0'
      '28': '373:16428'
      '29': '373:16388'
      '30': '373:16392'
      '31': '373:16394'
      '32': '0'
      '33': '0'
      '34': '0'
      '35': '0'
      names:
        '0': '&cStick of Wonder'

**Comment by lol768** [comment]
Firstly, thanks for using GitHub :smiley: 

I'm just going to check the code since I can't remember how to do this off the top of my head. I've answered this below:

**Comment by KylexDavis** [comment]
Thanks, will check back in a minute.

**Comment by lol768** [comment]
Right, the format is:
`itemID:amount:durability` Here, you're specifying 16394 glass bottles. Unfortunately the limit is 64 and you've probably upset Minecraft a bit by supplying such a large number :laughing: 

Try this:
`373:1:16428`

I'll re-open the ticket if you have any more issues.

**Comment by KylexDavis** [comment]
Thanks a bunch as usual, worked!
