### ISSUE TITLE
Problem with armorless classes

### ISSUE THREAD

**Issue by dotcurrency** [np98765/BattleKits#28]
So I am trying to make a class that has no armor but I run into problems. After making the sign and clicking it the items do not appear until I re-log. Users are then able to select more signs despite already picking one (this only occurs with no armor kits). Also when dropping items from one of these no armor kits the items seem to drop into the armor slots! (see:http://imgit.me/i/0F5b2q4.png)

I have tried these kits settings and all give me the issue.

medic:
active-in: all
items:
helmet: none
chestplate: none
leggings: none
boots: none
'0': '0'
'1': '373:1:16389'
'2': '297:3'
'3': '0'
'4': '0'
'5': '0'
'6': '0'
'7': '0'
'8': '0'
'9': '0'
'10': '0'
'11': '0'
'12': '0'
'13': '0'
'14': '0'
'15': '0'
'16': '0'
'17': '0'
'18': '0'
'19': '0'
'20': '0'
'21': '0'
'22': '0'
'23': '0'
'24': '0'
'25': '0'
'26': '0'
'27': '0'
'28': '0'
'29': '0'
'30': '0'
'31': '0'
'32': '0'
'33': '0'
'34': '0'
'35': '0'

medic:
active-in: all
items:
'0': '0'
'1': '373:1:16389'
'2': '297:3'
'3': '0'
'4': '0'
'5': '0'
'6': '0'
'7': '0'
'8': '0'
'9': '0'
'10': '0'
'11': '0'
'12': '0'
'13': '0'
'14': '0'
'15': '0'
'16': '0'
'17': '0'
'18': '0'
'19': '0'
'20': '0'
'21': '0'
'22': '0'
'23': '0'
'24': '0'
'25': '0'
'26': '0'
'27': '0'
'28': '0'
'29': '0'
'30': '0'
'31': '0'
'32': '0'
'33': '0'
'34': '0'
'35': '0'

**Comment by lol768** [comment]
Can you upload the config (kits & global) to pastebin and also provide any errors in the server log?

**Comment by xron89** [comment]
Its a simple fix just remove the lines between items: and '0' it works for me

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/28#issuecomment-11395487

> Its a simple fix just remove the lines between items: and '0' it works for me

Yeah, just remove them.
