### ISSUE TITLE
Kit list permission from OriKenig

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#30]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=340 (author: OriKenig) at Dec 13, 2012 at 10:16 UTC**

The permission BattleKits.listKits still dont work for me ..
I put it false and i use permission bukkit.
Are you sure ?
And can i change the [BattleKits] to what i want ?

**Comment by lol768** [comment]
I need to know which version of the plugin you are using.

**Comment by kenig** [comment]
I am using the 1.5 version of your plugin :)

**Comment by lol768** [comment]
Yeah, that's really outdated. Try the latest version here:
http://199.241.30.86/builds/
