### ISSUE TITLE
List Of Issues - 

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#31]
Hi, so my last thread type thing was messy here are some real issues, 

Issues ~

FIXED :: As far as I can see

Items are dropped on death and can be seen by all players but other players cant pick up others items, players can pick up there own items see the detail version down below. (needs testing again) 

RESOLVED
Ops respawn as a kit and are unable to change the kit they are forced as this kit forever 

Suggestions ~

Needs to include better reward support, giving X credits per kills means again your eco for the whole server is taken up by this plugins, needs its own reward credit system if thats a path to be chosen.

if you die from fire e.g. pyro kit then none gets a reward, a lot of rewards missed out because fire got the last hit.

Web support would be nice a simple mysql data base displaying kill death ration and top players for websites in an easy to read php format would really help.

**Comment by lol768** [comment]
Thanks for this. It's a lot cleaner and more helpful too.

> The plugin over rides everything for all worlds, so if you have this plugin your server can ONLY be a kit server, needs to work per world or at least have the setting to do so. 

We do support multi-world. Not sure which part you're referring to? Could you elaborate? Is it the restrictions, kits?

> You can mix kits, by selecting a kit then picking another really not good at all. 
> It clears your inventory if you define the kits properly. I'll add a config option in to make this a bit easier.
> 
> you can drop items but cant move invent, I know theres a thing in the config for invent movement but dropping items should be off aswell. 

Restrictions are handled by permissions:

```
BattleKits.bypassRestriction.disable-hunger
BattleKits.bypassRestriction.disable-dropping-items
BattleKits.bypassRestriction.disable-player-drops-on-death
BattleKits.bypassRestriction.disable-crafting
BattleKits.bypassRestriction.disable-player-xp-drop
BattleKits.bypassRestriction.disable-mob-xp
BattleKits.bypassRestriction.disable-block-xp
BattleKits.bypassRestriction.disable-inventory-interaction
BattleKits.bypassRestriction.disable-pickup-items
BattleKits.bypassRestriction.disable-block-break
BattleKits.bypassRestriction.disable-block-place
BattleKits.bypassRestriction.hide-death-messages
```

np98765 mentioned a credits system. I'm not sure about this yet. I'm getting the feeling it's beyond the scope of the plugin to a certain extent but it is a possibility. Rewards do allow any command and we also have kill streak support available now as well. Something to consider...

I'm not sure I can do anything about the fire, I don't know whether it's possible to actually find out who set fire to somebody.

Web support... Hmm. I will consider it but it will likely be with an internal web server and not MySQL. I think that would be the best way of doing it..

**Comment by lol768** [comment]
Another note, permissions can be handled multi-world, but that's up to your permissions plugin. I know bPermissions definitely supports this.

I'd setup a default group, give them `BattleKits.bypassRestriction.*` and then negate the particular nodes for your PvP world.

**Comment by lol768** [comment]
1.8.8 allows you to forcibly clear the user's inventory when they switch kits:
http://199.241.30.86/builds/

**Comment by xron89** [comment]
Thanks lol, I will look into the plugin a little deeper because all my players miss it, 

For the multi world issue, it wouldn't let my players build in another world, even though I check the config etc.. I'm going to install 1.8.8 now and test a few things for you I will post back within the hour explaining anything

**Comment by xron89** [comment]
Could you add some comments to the config I still dont know what some it means e.g. 

 enable-restrictions:

  ignore-permissions: false (signs)

  ignore-world-restriction: false (does that mean it is only on one world or :S confused)

**Comment by xron89** [comment]
Problem list will edit - 

Items drop on death, still

Players start with a kit, which means when they die and respawn as the kit they had last time, they cant change kit because they already have one! I turned this setting like this "once-per-life: false", so they could change kit but theres a bug! Thi bug is when you swap kit what ever item you have selected e.g slot 1 heavy sword switch to archer you get all the archer stuff apart from slot one because you had it selected.

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/31#issuecomment-11406266

> Could you add some comments to the config I still dont know what some it means e.g. 
> enable-restrictions:
> ignore-permissions: false (signs)
> ignore-world-restriction: false (does that mean it is only on one world or :S confused)

Enable restrictions completely disables or enables restrictions (such as item dropping, block placing etc). Set this to false if you don't want to use the restrictions. Ignore world restriction is a sign/indirect property that makes kit signs ignore the world restrictions you define in kits.yml (active-in line). Ignore permissions does the same but simply makes BattleKits.use.kitName ignored.

@xron89 https://github.com/np98765/BattleKits/issues/31#issuecomment-11406215

> Thanks lol, I will look into the plugin a little deeper because all my players miss it, 
> For the multi world issue, it wouldn't let my players build in another world, even though I check the config etc.. I'm going to install 1.8.8 now and test a few things for you I will post back within the hour explaining anything 

Once again, restrictions are handled by permissions. I'll take a look at your server.

**Comment by xron89** [comment]
Thanks I updated above with a bug

**Comment by lol768** [comment]
Right, I've immediately noticed you've **disabled restrictions**. This means that item drops, block placing etc will be allowed. I'm going to turn them on now.

**Comment by lol768** [comment]
The likely issue will be now that nobody can build or do anything.

**Comment by lol768** [comment]
I've added the permissions so item dropping should now be disabled in the factions world.

**Comment by xron89** [comment]
Okay thanks, will we be able to enable building?

**Comment by xron89** [comment]
yup

**Comment by lol768** [comment]
Reload GroupManager, I've setup basic permissions to allow this

**Comment by xron89** [comment]
Will do thanks

**Comment by xron89** [comment]
Edit, for some reason ops start with a kit, which means they cant change kit but only ops i'm checking the config

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/31#issuecomment-11409984

> Edit, for some reason ops start with a kit, which means they cant change kit but only ops i'm checking the config

This is because auto kit giving is handled by permissions:
`BattleKits.auto.kitName` - You'll need to negate this permission for operators until I can sort it out

**Comment by xron89** [comment]
how do I negate it I remove it from there groups dont I need to add something like ignore.BattleKits.auto.kitName

**Comment by lol768** [comment]
I honestly have no idea, one min while I look it up

**Comment by xron89** [comment]
Thanks!

**Comment by xron89** [comment]
I think theres a bug to do with your plugin, players on my factions world are not getting xp from mobs is that something battlekits could be overriding

**Comment by lol768** [comment]
Fixed. Please reload essentials

**Comment by xron89** [comment]
Thanks!

**Comment by xron89** [comment]
I just noticed an issue, I setup a small shop to allow people to buy potions to help them in the pvp arena, they could buy these with there pvp points! but they cant move there inv around as the potion gos to the last free slot which is in the inv. I dont see the config settign to enable move stuff in inv so they can bring potions to the hot bar

**Comment by lol768** [comment]
Made a few mistakes in the config. Sorry.

New permission is `BattleKits.bypassRestriction.disable-inventory-click` Make sure they have that (add it in group manager config for factions).

Build available from http://199.241.30.86/builds/

**MAKE SURE YOU CHOOSE 1.8.9, IT'S NOT AT THE TOP**

**Comment by xron89** [comment]
I will try my best to explain this for you sorry if I cant hehe

Okay so you kill 15 people you have now got 15 credits, you go to the shop on the same world and buy a potion for 15 credits, the problem before was you couldn't move items around your invent so when you got the potion it went to your last free invent slot and you couldn't get it onto your hot bar. Note this is all in the pvp battlekits world. 

So I downloaded build 1.8.9 and added the above permission to both worlds so people can move items in there invent, This has bought up an issue where by a player can become a heavy drop the sword which I'm 99.9% sure only he can see on the floor and only that player who dropped the item can pickup. He then dies as a heavy with the sword on the floor and picks an archer he then picks up the sword which is still on the floor. 

Way to fix this issue, block dropping items but allow invent moving. 

Any entities dropped on the floor are instantly removed. (make sure its per world though of course)

Thanks, hit me back with any question though u'm likely to be offline within an hour 

Thanks!

**Comment by xron89** [comment]
Edit - sorry for working you over time hehe your the best and this plugin can be the best! I will make some public kits to share with your users tomorrow

**Comment by xron89** [comment]
Updated the list above

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/31#issuecomment-11412103

> I will try my best to explain this for you sorry if I cant hehe
> Okay so you kill 15 people you have now got 15 credits, you go to the shop on the same world and buy a potion for 15 credits, the problem before was you couldn't move items around your invent so when you got the potion it went to your last free invent slot and you couldn't get it onto your hot bar. Note this is all in the pvp battlekits world. 
> So I downloaded build 1.8.9 and added the above permission to both worlds so people can move items in there invent, This has bought up an issue where by a player can become a heavy drop the sword which I'm 99.9% sure only he can see on the floor and only that player who dropped the item can pickup. He then dies as a heavy with the sword on the floor and picks an archer he then picks up the sword which is still on the floor. 
> Way to fix this issue, block dropping items but allow invent moving. 
> Any entities dropped on the floor are instantly removed. (make sure its per world though of course)
> Thanks, hit me back with any question though u'm likely to be offline within an hour 
> Thanks!

Sounds like the inventory is not refreshing :frowning:. Not sure what I can do about it.

I've also asked [some people](http://forums.bukkit.org/threads/removing-permission-from-operators-by-default.116270/) about sorting the permissions out. I'll let you know if I get anything.

@xron89 https://github.com/np98765/BattleKits/issues/31#issuecomment-11412122

> Edit - sorry for working you over time hehe your the best and this plugin can be the best! I will make some public kits to share with your users tomorrow

Thanks :smile:

**Comment by xron89** [comment]
check my first post I added a faction build glitch again now sure why it is this time

**Comment by xron89** [comment]
Been trying a few things to get building working in factions with no luck still grr :(

**Comment by lol768** [comment]
It's permission based, make sure every one has `BattleKits.bypassRestriction.disable-block-place`

**Comment by xron89** [comment]
Okay I added that, I also added 

```
- BattleKits.bypassRestriction.disable-inventory-click
- BattleKits.bypassRestriction.disable-block-place
```

The invent click could that be stopping it to because those 2 together didnt fix it :(

**Comment by xron89** [comment]
it didn't seem to work is there a BattleKits.bypassRestriction.disable-block-break too?

**Comment by lol768** [comment]
Yes.

**Comment by xron89** [comment]
Omg it worked I just need the bypass for picking up blocks now then its done!!!! freaking out

do you know what it is to pick up blocks and items

**Comment by lol768** [comment]
:smile:

Picking up items? `BattleKits.bypassRestriction.disable-pickup-items`

I'm rewriting the download tracker at the moment so I can do more development builds faster etc. Then I'll have a short break for Christmas and I can start adding some of your features.

**Comment by xron89** [comment]
Sweet thanks! Merry christmas and all!

**Comment by xron89** [comment]
Last thing I swear people cant craft is there a bypass for crafting maybe 
BattleKits.bypassRestriction.disable-crafting

I'm not sure eek

**Comment by lol768** [comment]
@xron89 Yeah, that permission is correct.

**Comment by xron89** [comment]
Thanks I also managed to work out the dropping items bypass too :) all is good so far I will update post 1# if my players find anything new

**Comment by lol768** [comment]
Please use negative nodes for operators to remove the auto permissions from them:
E.g. -BattleKits.auto.*
Stops all kits from being automatically given back.

I'm going to close this ticket and open separate issues for your suggestions.

Thanks,
lol768
