### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by ghost** [np98765/BattleKits#32]
Hello, my players have no permissions to the kits? I'm an experienced user of PeX, been using it for 2 years. Never had any problems with it, but the permissions at BattleKits does not work at all ?? 

PeX works just great with the other plugins, does BattleKits not accept Pex? or..? please help..

PeX Group:

  donator:
    default: false
    permissions:
    - PlayerStatus.afk
    - PlayerStatus.nochat
    - PlayerStatus.nomsg
    - PlayerStatus.ignore
    - BattleKits.sign.use
    - commandbook.kit.list
    - commandbook.kit.pvp
    - commandbook.kit.archer
    - commandbook.kit.kits.archer
    - commandbook.kit.kits.pvp
    - commandbook.kit
    - commandbook.msg
    - commandbook.rules
    - iConomy.rank
    - instaeat.instaheal
    - iConomy.list
    - iConomy.holdings
    - ChestShop.shop.buy
    - ChestShop.shop.sell
    - commandbook.motd
    - commandbook.time.check
    - Sidekick.world
    - BattleKits.sign.use
    - BattleKits.use.pyro
    - BattleKits.use.<pyro>
    - BattleKits.use.archer
    - BattleKits.use.<archer>
    - BattleKits.use.heavy
    - BattleKits.use.<heavy>
    - BattleKits.use.ninja
    - BattleKits.use.<ninja>
    - commandbook.time
    prefix: '&b[&6Donator&b]&d'

**Comment by ghost** [comment]
Please help :/
Not ignoring you, just been ill. Looking into it, please check back tomorrow.

**Comment by lol768** [comment]
As said, I wasn't able to look into this earlier as I've had other things to worry about. We're not ignoring you, but it's approaching Christmas and we have other things to contend with.

Firstly:
- BattleKits.use.

is a malformed node. You haven't supplied anything to the end of it.

Please upload the actual yaml file to something like dropbox so it can be analysed.

**Comment by lol768** [comment]
Closing this now, feel free to provide more info and I'll reopen
