### ISSUE TITLE
Death event and the attacker

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#33]
if you die from fire e.g. pyro kit then none gets a reward, a lot of rewards missed out because fire got the last hit.

Need to check if this is possible first. It's somewhat unlikely but I should be able to get projectiles etc to work.

**Comment by xron89** [comment]
Yeah annoying I looked at your notes and it looks like it could be a hard fix

**Comment by lol768** [comment]
I've done as much as I can on this - unfortunately there are too many factors involved to get killers who used fire etc. This i also somewhat outside the scope of the plugin.
