### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#34]
Web support would be nice a simple mysql data base displaying kill death ration and top players for websites in an easy to read php format would really help. 

Jetty.

**Comment by xron89** [comment]
Agree +1

**Comment by lol768** [comment]
Working on this now :smile:

What information exactly do you want to see @xron89?

**Comment by xron89** [comment]
Hi, suggestion would be display the out put in a table as 
username 
kills
deaths
Kill death ratio (K/D) 

the table would be populated via highest K/D first I guess 

It would be nice if this was built via bootstrap I think you have used it before ;) and I use it for my server stie (www.epic-pvp.com) 

Thanks!

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/34#issuecomment-11755785

> Hi, suggestion would be display the out put in a table as 
> username 
> kills
> deaths
> Kill death ratio (K/D) 
> the table would be populated via highest K/D first I guess 
> It would be nice if this was built via bootstrap I think you have used it before ;) and I use it for my server stie (www.epic-pvp.com) 
> Thanks!

Already using Bootstrap :smile: Sounds good

**Comment by xron89** [comment]
Awesome, will it use mysql to capture kills etc.. I cant wait to see this added

**Comment by lol768** [comment]
YAML with a JSON API

**Comment by xron89** [comment]
Sweet, I'll make a video guide if it is a little tricky for non web people, do you have any eta on when this might be added to the plugin, or is it going to be implemented slowly over the next 2 or so months

**Comment by lol768** [comment]
Very simple, bare bones version has been added in 2.0, but I still need to make it sort the table by kill percentage. Feedback would be awesome!

**Comment by xron89** [comment]
Okay cool, I will spam out your github with errors etc..by the end of this weekend I'm currently switching ISP, I get my net back on thursday where I will test all of this for you!

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/34#issuecomment-13395529

> Okay cool, I will spam out your github with errors etc..by the end of this weekend I'm currently switching ISP

Should I be worried? :smile:

In all seriousness, thanks a bunch for testing all this out for me. It really helps. Hope the ISP change works out for you

**Comment by xron89** [comment]
Could I get a link or is there a download somewhere to add this to our site?

**Comment by lol768** [comment]
It runs by default on whatever port you have set in your config - see under server in global.yml - it's completely built in.

**Comment by xron89** [comment]
im confused so what do we put on our site to display the table, my port is 8080 in the config

**Comment by lol768** [comment]
What's your IP?

**Comment by xron89** [comment]
188.165.232.156:25566 thats my ip

**Comment by lol768** [comment]
http://188.165.232.156:8080/

**Comment by lol768** [comment]
It does need a lot of work, but that's what it initially looks like.

**Comment by xron89** [comment]
I have had over 10k players on my server I take it this only displays the top players in an unordered list?

**Comment by lol768** [comment]
Have they all died/killed?
This is since you enabled BattleKits?

**Comment by lol768** [comment]
Concept cancelled.
