### ISSUE TITLE
Kit sign issues from hehehehe123123

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#35]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=365 (author: hehehehe123123) at Dec 20, 2012 at 10:16 UTC**

i cant use the sign but
i can use /bk (class)

**Comment by lol768** [comment]
Please post your global.yml file

Make sure signs.enabled is true

**Comment by hehehe123123** [comment]
ok lol768
here

global.yml = http://pastebin.com/kY5NeCp3
kits.yml = http://pastebin.com/YXFCma5z

**Comment by zzkanezz2** [comment]
Yup signs don't work..

**Comment by zzkanezz2** [comment]
Never mind got them to work! Sorry.

**Comment by np98765** [comment]
Closing this issue; feel free to reopen if you have further problems.

**Comment by hehehe123123** [comment]
can you tell me whats wrong? please i really need help with that
awesome plugin

**Comment by lol768** [comment]
Fixed global.yml:
http://pastebin.com/MCnRTaJG

**Comment by hehehe123123** [comment]
lol how can you set a reward?
for example by default the reward is XP right?
Im gonna change my reward to HEAD or MONEY
can you do that?

**Comment by lol768** [comment]
@hehehe123123 https://github.com/np98765/BattleKits/issues/35#issuecomment-11636086

> lol how can you set a reward?
> for example by default the reward is XP right?
> Im gonna change my reward to HEAD or MONEY
> can you do that?

BattleKits allows you to use any number of commands for rewards. If you upload your global.yml I'd be happy to show you.
