### ISSUE TITLE
Folder Not Being Generated

### ISSUE THREAD

**Issue by DonyorM** [np98765/BattleKits#36]
I put the jar in my /plugins folder but no config folder is being generated. Why?

**Comment by lol768** [comment]
I have no idea. A server log file would probably help.

In future, please check to see if your post meets the issue guidelines: https://github.com/np98765/BattleKits/issues/1

**Comment by lol768** [comment]
Install Java 7, get the latest build from:
http://199.241.30.86/builds/

Use latest recommended CraftBukkit
