### ISSUE TITLE
1.4.6 Recode

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#37]
Hi,
a lot of bugs with craftbukkit Version 1.4.6 I will post them as we go, but theres lots! Eek I know its christmas so I wont expect anything its holiday time! A lot of other plugins are in the same boat! 

Don't listen to anything i said the new update you put out seems to work fine

**Comment by lol768** [comment]
> Don't listen to anything i said the new update you put out seems to work fine

Can I close the issue then :smile:?

Dev builds are at http://199.241.30.86/builds/

**Comment by xron89** [comment]
I guess hehe sorry

**Comment by lol768** [comment]
Well that was an easy issue to resolve :grinning:
