### ISSUE TITLE
Auto give back

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#38]
Hi, my internet has been down for a few days and I have missed a lot I just tried your auto give back fix. 

Please use negative nodes for operators to remove the auto permissions from them:
E.g. -BattleKits.auto.*
Stops all kits from being automatically given back.

I still get given a kit, so do my ops

**Comment by lol768** [comment]
Can I see your permissions config?

**Comment by xron89** [comment]
Sure here - http://pastebin.com/19XSWbz4

Also if you ally with a faction of have team mates in your faction you can't fight each other I guess thats not to do with your plugin though

**Comment by lol768** [comment]
Your groupmanager config, sorry.

**Comment by xron89** [comment]
Global - http://pastebin.com/0N7aMJsq
Factions - http://pastebin.com/qQN0uw7k
normal pvp world - http://pastebin.com/W9Kszb9z

**Comment by lol768** [comment]
You're not taking away BattleKits.auto.*, you're giving it which is why it doesn't work.

**Comment by lol768** [comment]
See: http://pastebin.com/raw.php?i=CnzqiqUK

**Comment by lol768** [comment]
Closing unless problems persist.

**Comment by xron89** [comment]
Hi, It still doesn't work I tried what you said, I spawn with a kit it says I can use a new kit then I try a new kit and says I can only use one per life I also made a thread with more bugs
