### ISSUE TITLE
Permission Nodes do not work

### ISSUE THREAD

**Issue by J0DC** [np98765/BattleKits#39]
By default, no matter what I change in the config, and what permissions node I give to the groups in my server, they cannot move their inventory, or do any of the restricted actions.

**Comment by lol768** [comment]
So they can't place blocks or anything?
Can I see your permissions config pelase?

**Comment by J0DC** [comment]
I don't want to them to place blocks, but I want them to be able to move their inventory.
It's a KitPvP server.
I use GroupManager for permissions. I only have 2 groups available to normal players, and they both have the permission
"BattleKits.bypassRestriction.disable-inventory-interaction"

**Comment by lol768** [comment]
Version?

**Comment by J0DC** [comment]
I am using the 1.4.6 Beta CB and 1.9.1 Battlekits for 1.4.6

**Comment by lol768** [comment]
BattleKits.bypassRestriction.disable-inventory-click

Is the correct node.

**Comment by J0DC** [comment]
Thank you so much, but could you give me the other nodes for future reference?

**Comment by lol768** [comment]
BattleKits.bypassRestriction.disable-hunger
BattleKits.bypassRestriction.disable-dropping-items
BattleKits.bypassRestriction.disable-player-drops-on-death
BattleKits.bypassRestriction.disable-crafting
BattleKits.bypassRestriction.disable-player-xp-drop
BattleKits.bypassRestriction.disable-mob-xp
BattleKits.bypassRestriction.disable-block-xp
BattleKits.bypassRestriction.disable-inventory-click
BattleKits.bypassRestriction.disable-pickup-items
BattleKits.bypassRestriction.disable-block-break
BattleKits.bypassRestriction.disable-block-place
BattleKits.bypassRestriction.hide-death-messages

**Comment by lol768** [comment]
I still need to check them though. If you're able to, the code is a better reference:
https://github.com/np98765/BattleKits/blob/master/BattleKits/src/com/lavacraftserver/BattleKits/RestrictionEvents.java

**Comment by lol768** [comment]
This is poorly documented. I've added a better reference to the FAQ. Thanks for using BattleKits :smile:
