### ISSUE TITLE
Exp not dropping

### ISSUE THREAD

**Issue by zzkanezz2** [np98765/BattleKits#4]
CraftBukkit version: #2455 1.4.2 Beta Build
Plugin list: http://i48.tinypic.com/168izc1.png
BattleKits version: Latest R: BattleKits 1.3.3 (Security update) for CB 1.4.2-R0.2 1 day ago
Config file link (pastebin.com): http://pastebin.com/08URGpZn
Server log link (pastebin.com): http://pastebin.com/yM51MnWd

When does the error occur? When I installed battlekits

Steps to reproduce error: Just have exp drops set to true and disabled..

Any other relevant info: Exp just isn't dropping when it should be in the config, I've tried toggling some of the other plugins and removing but I think it's actually just the battlekits plugin. Hopefully it can get sorted thanks!

**Comment by lol768** [comment]
I'll update you on this later on.
Sorry for any inconvenience.

**Comment by lol768** [comment]
I can't confirm this with the latest dev build. Try installing this build: http://www.filedropper.com/battlekits
Your config looks ok. If you modify it, make sure you do /bk reload otherwise it will simply get overwritten when you next do a /reload or restart the server.

**Comment by zzkanezz2** [comment]
Tried, doesn't work :_(

**Comment by zzkanezz2** [comment]
Tried the download as well :_(

**Comment by lol768** [comment]
How are you testing it?
I'll make you a build with the xp functionality entirely disabled: http://www.filedropper.com/battlekitsxpforced
If that build doesn't work, nothing will.

**Comment by zzkanezz2** [comment]
The thing that could be preventing it would be essentials but I've disabled all flags and what not to see if anything was causing it, and also took out a few plugins like no drops ect. to see if that would fix the issue. Tried opposite of false to try. I'll give that a try.

**Comment by lol768** [comment]
Ok, tell me how if it fixes the issue.

**Comment by zzkanezz2** [comment]
When I install that one and the previous one, players can select any kit, such as the VIP only kits. Seems to allow them to use them all.

**Comment by lol768** [comment]
Damn, just found the bug. Thanks for telling me. Fixed.
New build: http://www.filedropper.com/battlekitsxpforced_1

**Comment by zzkanezz2** [comment]
Okay permissions fix, back to default BattleKits.use.<kitname> very nice. Testing experience now.

**Comment by zzkanezz2** [comment]
Nope doesn't work :s

**Comment by lol768** [comment]
Then it's not my plugin.

I completely removed every reference to xp in that build.

**Comment by zzkanezz2** [comment]
Should exp work in the version you gave me?

**Comment by lol768** [comment]
Yes, all xp should be available in the build I sent you, regardless of whether you've disabled it in the config or not.

I commented all the xp code out:

``` java
    @EventHandler
    public void death(PlayerDeathEvent e) {
        if (plugin.getConfig().getBoolean("settings.disable-player-xp-drop"))
            //e.setDroppedExp(0);

        if (plugin.getConfig().getBoolean("settings.disable-player-drops-on-death"))
            e.getDrops().clear();

        if (plugin.getConfig().getBoolean("settings.hide-death-messages"))
            e.setDeathMessage(null);

    }

    @EventHandler
    public void mobDeath(EntityDeathEvent e) {
        if (!(e.getEntity() instanceof Player)) {
            if (plugin.getConfig().getBoolean("settings.disable-mob-xp-drop")) {

                //e.setDroppedExp(0);
            }
        }
    }

    @EventHandler
    public void blockBreak(BlockBreakEvent e) {

        if (plugin.getConfig().getBoolean("settings.disable-block-xp"))
            //e.setExpToDrop(0);

        if (plugin.getConfig().getBoolean("settings.disable-block-break"))
            e.setCancelled(true);

    }
```

**Comment by zzkanezz2** [comment]
I see. Then it's most likely not the plugin if all this is set up like this. Strange I can't seem to find what's causing it from not dropping that I haven't tried. I'll further continue my test. Last question, does the exp drop or go directly into there exp bar?

**Comment by lol768** [comment]
XP normally drops. When BattleKits disabled it, none will drop at all.

**Comment by lol768** [comment]
Found not to be BattleKits.
