### ISSUE TITLE
List Of Issues -

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#40]
BattleKits Bug List By ME! Version 3.1! 

Ops are still getting kits back for example I pick heavy kit, I'm now stuck with heavy forever! 

This is the config - http://pastebin.com/jdXpH9Ud
Console Bugs - N/a
Group Permissions given - none yet
Bug Live: Yes. Confirmed

Players are given an empty bowl and sometimes have to relog to see the kit they have picked

This is the config - http://pastebin.com/jdXpH9Ud
Console Bugs - N/a
Group Permissions given - none yet
Bug Live: On an older build

Players drop items on death

This is the config - http://pastebin.com/akgFszVL
Console Bugs - N/a
Group Permissions given - none yet
Bug Live: Confirmed items drop with ops, unconfirmed default players

There are other bugs just need to confirm and test these on the latest build

**Comment by lol768** [comment]
> Ops still cant use a kit, they are forced with the same kit over and over again.
> 
> people on other worlds get kits
> 
> Ops respawn with kits in other worlds. 

This is a permissions configuration issue.

I'll look into the kit issue

**Comment by xron89** [comment]
also I cant add new kits, when I do it says it doesnt exist the kit file returns no yml errors

**Comment by lol768** [comment]
I'll look into this after Christmas

**Comment by xron89** [comment]
thanks ^^

**Comment by xron89** [comment]
Also this keeps being overlooked but a big bug is the fact you have to have one kit per life to true else you can swap kits I would really like to see this working. E.g you can swap kits as many tiems as you want but it needs to comepletely clear your invent before it issues the new one. It would also need to stop people dropping items or if oyu drop items they get removed or you cant pick them back up

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11687783

> Also this keeps being overlooked but a big bug is the fact you have to have one kit per life to true else you can swap kits I would really like to see this working. E.g you can swap kits as many tiems as you want but it needs to comepletely clear your invent before it issues the new one. It would also need to stop people dropping items or if oyu drop items they get removed or you cant pick them back up 

One kit per life should be disabled if you want to do this. We have an option called clearInventory that allows you to clear inventories between kit changes (in global.yml). This combined with the restriction events may help.

**Comment by xron89** [comment]
Thanks for the comment, the latest build didn't add any text to config file apart from the top 5 lines which are comments, i pasted in the config settings from my older build and signs dont work Eek!
I also never got kill streaks working might be something to add to the list

**Comment by xron89** [comment]
using 1.9.3 i still get no config these are the only lines in the config when generated from the jar - 
"# Global BattleKits settings"
"# Add world-specific blocks by warapping everything in the name of the world."
"# Restrictions are handled by permissions now."

**Comment by lol768** [comment]
Definitely looking into this. For reference, see the global.yml file on github (in the actual code).

Thanks

**Comment by xron89** [comment]
Thanks, If you ever need a server to run any test, I have a dedicated now which I can split down its 32gb I think I have around 14gb left over at the moment :)

**Comment by xron89** [comment]
I know you said to use the debug version if you have sign issues, but to note that version 1.9.3 also doesn't work for signs using this config - 

http://pastebin.com/akRkpP9Z

**Comment by lol768** [comment]
Do they not work at all?

**Comment by xron89** [comment]
No dont even go red using the correct format have a look if you like kit.epic-pvp.com:25566

**Comment by xron89** [comment]
Dropped you a pm on bukkit ^^

**Comment by lol768** [comment]
Can you remove line 5 of your config and do a /bk reload?

**Comment by xron89** [comment]
Sure 1 second

**Comment by lol768** [comment]
Also, turn off auto update - it breaks everything :'(

**Comment by xron89** [comment]
Done both still nothing on the signs no red text

**Comment by lol768** [comment]
Anything in the console/server log?

This the 100 slot server?

**Comment by xron89** [comment]
Yeah it is, the gamepanel is being update give you console check in a second

**Comment by xron89** [comment]
We have errors - http://pastebin.com/i8aGjADX

**Comment by xron89** [comment]
Something about a sepcial charcter - "„"  theres nothing using that charcter in my config

**Comment by lol768** [comment]
Try deleting the messages section?
I'll look at this on your server tomorrow anyway :-)

**Comment by xron89** [comment]
Using this config now  - http://pastebin.com/nXQPBXC1

Signs dont work still, but I have noticed i can do "/bk heavy" and I do get the kit note i didn't try run this command before I removed the messages so it might have worked before anyway. 

This is the server log with the messages removed 

-http://pastebin.com/7mMmHJ1N

**Comment by xron89** [comment]
No errors with the messages section removed, I had a suggestion of moving that to another yml file as the config started to get cluttered ^^ 
Thanks feel free to take a look note signs still not working with no errors 

Thanks!

**Comment by lol768** [comment]
I've removed the languages from the entire plugin. This seems to have fixed some config bugs. Can you try signs on the bottom server now?

**Comment by xron89** [comment]
Yup signs are now working once again nice job! I'll update the top post

**Comment by xron89** [comment]
Okay, updated the first post much better now going to test this a little more. I think you told me how to fix the op glitch so i do apologize I have forgotten :(

**Comment by xron89** [comment]
I'm unable to add new kits in the latest build and in older builds 
kit config - http://pastebin.com/i4EKhNUs

**Comment by lol768** [comment]
What happens? Is the config reset? Do they not appear in the list after a bk reload? Anything in the console?

**Comment by xron89** [comment]
Ahh it says the kit does not exist but it says it for heavy sign too, so I think its all broken :(

**Comment by lol768** [comment]
I'll do some extensive testing tomorrow

**Comment by xron89** [comment]
Thanks!!! cant wait

**Comment by xron89** [comment]
Any luck because at the moment the plugin is broken Ahh :(

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11742514

> Any luck because at the moment the plugin is broken Ahh :(

I've been having the issues you've described. What I'm probably going to do is setup a clean test server and test every individual component of the plugin individually. I've got a checklist which includes things like:
- Plugin can startup and generate all 3 config files
- Kits with plugin can be used
- All restrictions can be setup and bypassed or enforced
- Kits can be added to the config with:
  - 4 armours
  - 2 armours
  - No armour
  - 0 items
  - 5 items
  - 10 items
  - Whole inventory
- Kits are added and are visible with a /bk reload
- Kit signs can be created
- Kit signs work as expected

And on. This might take some time but it should hopefully identify and fix any and all bugs.

Cheers for your patience, I know it's frustrating.

**Comment by xron89** [comment]
Thanks for keeping this updated I knwo you have no duty to post here each day but its refreshing to see new posts here :)

**Comment by lol768** [comment]
The testing is scheduled for tomorrow at 10AM, GMT. Convert it to your time [Here](http://tinyurl.com/bwvgh9f).

Link so you can see my progress if you want to: https://docs.google.com/spreadsheet/ccc?key=0Ai8_JDvk_gAjdHppTThrMFZ4RmdhVTBzZUR3a3QtMEE

At least you know I'm not ignoring you :smile:

**Comment by lol768** [comment]
Actually, that might work better with timezones etc. Yeah - rescheduled. Also gives me some more sleep

**Comment by lol768** [comment]
Testing is done :D
https://docs.google.com/a/infinitenight.net/spreadsheet/ccc?key=0Ai8_JDvk_gAjdHppTThrMFZ4RmdhVTBzZUR3a3QtMEE#gid=0

And the resultant new build (1.9.5):
http://199.241.30.86/builds/index.php

![Image](http://i.imgur.com/rDl8g.png)

**Comment by xron89** [comment]
Woah loads of bugs fixed really nice! Going to give it a test now I'll get back to you if I find anything new! Thanks so much really thanks!

**Comment by xron89** [comment]
Could you maybe comment in the config a little more I had my own personal config where I added my own comments but I removed it by mistake and I forgot how to setup the config again, I still have a few errors

**Comment by lol768** [comment]
The actual config in the JAR file is fully commented. Unfortunately, it automatically strips all of the comments out :cry: 

I might upload a version somewhere.

**Comment by xron89** [comment]
Yeah be nice my ops are spawning with kits again, and items are dropping on death what I found so far =]

**Comment by xron89** [comment]
Changed the config and it stopped ops getting kits back but its come back because I chnaged something again GR

**Comment by xron89** [comment]
Yeah I even tried the old configs, could you take a look on my server pls :) I can top up funds if it works hehe

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11756629

> Yeah I even tried the old configs, could you take a look on my server pls :) I can top up funds if it works hehe 

The bottom one?

**Comment by xron89** [comment]
Yes, the 100 slot bottom not the 10 ^^

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11757327

> Yes, the 100 slot bottom not the 10 ^^

Ok, which of these do you want?
Disable placing blocks
Disable breaking blocks
Disable getting xp from mobs
Disable getting xp from blocks
Hide death messages
Disable food from going down
Disable crafting
Disable moving items around in the inventory
Disable dropping items on death
Disable dropping items with q or dragging out of inventory
Disable picking up dropped items

**Comment by xron89** [comment]
I dont need any of these they can be disabled/turned off
Disable placing blocks
Disable breaking blocks
Disable getting xp from mobs
Disable getting xp from blocks
Hide death messages
Disable food from going down
Disable crafting
 Disable dropping items on death
Disable dropping items with q or dragging out of inventory
Disable picking up dropped items

Only one I would like is move items around so I can give more items then just on the hot bar thanks!!

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11757525

> I dont need any of these they can be disabled/turned off
> Disable placing blocks
> Disable breaking blocks
> Disable getting xp from mobs
> Disable getting xp from blocks
> Hide death messages
> Disable food from going down
> Disable crafting
>  Disable dropping items on death
> Disable dropping items with q or dragging out of inventory
> Disable picking up dropped items
> Only one I would like is move items around so I can give more items then just on the hot bar thanks!!

I'm a bit confused. so you don't want to stop them placing blocks. I.e. you want to let them place blocks?

**Comment by xron89** [comment]
I mean I do want to stop them doign the list above

**Comment by xron89** [comment]
I dont want them to place blocks sorry my bad! 

I only want them to be able to move items in the inv

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11757595

> I dont want them to place blocks sorry my bad! 
> I only want them to be able to move items in the inv

So I'll stop them from doing everything else then.

Do you want them to lose food or not?

**Comment by xron89** [comment]
I would like it if they didn't lose hunger if thats what you mean :)

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/40#issuecomment-11757609

> I would like it if they didn't lose hunger if thats what you mean :)

Looks setup to me. Nitram wants you to admin him though.

**Comment by xron89** [comment]
Ahh, hehe thanks lemme check it out

**Comment by xron89** [comment]
Sorry I forgot to note down that permission that allows a player to build destroy / place blocks 

thanks!

**Comment by xron89** [comment]
sorry ^^

**Comment by lol768** [comment]
Hmm, let me look it up

**Comment by lol768** [comment]
BattleKits.bypassRestriction.disable-block-break

**Comment by xron89** [comment]
Thanks! I tried to add a kit with potions but when I add this kit it breaks when I remove it its fine so there is an issue with this kit but im not sure what hmm..

http://pastebin.com/xmtLEpbV

**Comment by xron89** [comment]
I ran a yml check and it came back with this erorr, but i'm not sure if the battlekits kits file uses yml 

http://wiki.ess3.net/yaml/35034

**Comment by xron89** [comment]
http://pastebin.com/JU50M7BL 

This was an error I got somone click archer kit and ended up with billions of xp flying around his head might be something of intrest to you

**Comment by lol768** [comment]
The xp showering is a feature :-) 

TagAPI appears broken - not sure why. I'll try contacting the developer again.

**Comment by xron89** [comment]
Okay sure I was just checking what it was, i removed the xp feature from the archer kit that shouldn't be a problem anymore :)
Dont worry abotu the tag api thing it will work when it works :+1:

**Comment by lol768** [comment]
Hehe, it was a nice fun feature to add :-) 

I don't think it's my fault but I'll try and fix it anyway :smile:

**Comment by lol768** [comment]
I think we're don here, wow - over 50 comments. Feel free to open an issue if you have any other problems.
