### ISSUE TITLE
BattleKits won't work properly

### ISSUE THREAD

**Issue by JimBean** [np98765/BattleKits#41]
Well, the kits stuff does work but only the crafting, inventory editing stuff, the no hunger and all the other functions don't work. Im running the latest BattleKits build same as latest Spigot. Well, one of the first versions of BattleKits had working no-inventory-edit and so on festures i dunno why you guys removed these features. Also: no errors in Console at all.
If you could help me fix the BattleKits error it would be very kind of you.

**Comment by lol768** [comment]
RTFAQ.

**Comment by JimBean** [comment]
Read the FAQ? Well i did the one on the devbukkit site and it didn't help me yet. Gonna see if the one on here will fix the problem though.
