### ISSUE TITLE
Global.yml empty

### ISSUE THREAD

**Issue by JimBean** [np98765/BattleKits#42]
Hello. I wanna know what to fil into the global.yml - it's crappy documented/missing -, so anyways, the config.yml was generated in former versions and did work once [!] but now it's just empty, even with the latest BattleKits versions. I really would be happy if you guys from the BattleKits development could help me with the empty global.yml file. Thanks.
BattleKits: #1.9.1
Spigot: #3.6.2
[CraftBukkit: #2570]
MineCraft: 1.4.6
Thanks you.

**Comment by lol768** [comment]
Delete the file and then do /bk reload

It should re-generate. It's not supposed to be documented because you shouldn't need to add it yourself. 

Server log?

**Comment by JimBean** [comment]
Nah its empty under the #comments . Where the heck is the normal config file gone? The restrictions aren't working and i can't even configure them without an config file -.-

**Comment by lol768** [comment]
Server log please from when you've deleted the global.yml file and started up from fresh.

Restrictions are handled by permissions - not config.

**Comment by JimBean** [comment]
http://pastebin.com/61dj8mfp
Also, i would like to have an better documentation of what to really add to the global.yml since this file seems to be useless much.

**Comment by xron89** [comment]
I don't mean to hijack this thread but, this has now been fixed in the latest dev build you can download dev builds here - http://199.241.30.86/builds/index.php

Thanks

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/42#issuecomment-11713695

> I don't mean to hijack this thread but, this has now been fixed in the latest dev build you can download dev builds here - http://199.241.30.86/builds/index.php
> Thanks 

Thanks xron89 :smile: Wanna take over support for me? :grin:
