### ISSUE TITLE
Kit durability still being set when no armour is supplied, leading to NPE

### ISSUE THREAD

**Issue by J0DC** [np98765/BattleKits#44]
I still can't set a kits armor to nothing...
Could you actually tell me how to do it?
What i'm trying to make the kit do is have only a helmet and boots.

**Comment by lol768** [comment]
I don't really understand how this is difficult.. _This didn't really aid in solving the problem, sorry._

Just remove the chestplate and leggings lines from your kit config

**Comment by J0DC** [comment]
**:: All caps messages do not help solve the issue in any way. ::**

IT DOESN'T WORK.
I DELETED THE ARMOR THAT I WANT BLANK FROM THE KITS FILE AND IT MAKES THE WHOLE KIT HAVE NOTHING.

**Comment by lol768** [comment]
You obviously didn't delete it properly. I would be willing to work with you to solve this but writing unhelpful messages in all capitals on Christmas day when I'm obviously going to be busy with other things does not help at all.

If you want this solved, great - upload your kit config to pastebin and I'll take a look at it when I'm not busy. Otherwise continue to write unhelpful messages and I'll ignore you. 

Have a nice Christmas,
Lol768

**Comment by J0DC** [comment]
I'm sorry, but I've been dealing with this for ages.
How should I delete it?
This is what I have so far.
http://pastebin.com/2UufEfk7

**Comment by lol768** [comment]
And that breaks the entire kit? Interesting, can you try:
- Wrapping diamond in single quotes (e.g. 'diamond')
- Also please try adding in the chestplate and leggings but set them to 'none'

I can understand how frustrating it can be.

**Comment by J0DC** [comment]
I've tried those both. No avail.

**Comment by lol768** [comment]
Can I see the server log?

**Comment by lol768** [comment]
Found the issue, sorry about this - it was indeed my fault. Line 433 onwards of CommandBattleKits.java is the start of the faulty code. It is essentially trying to set the damage value of the armour without checking if the armour has been set or not. I'll try and fix this tomorrow.

Thanks for using BattleKits.

**Comment by J0DC** [comment]
Okay. No problem. Can you comment here when it's fixed?

**Comment by lol768** [comment]
Sure, will do. Should be a simple fix hopefully.

**Comment by lol768** [comment]
Fixed. Get the latest build from the usual place.

**Comment by lol768** [comment]
http://199.241.30.86/builds/dl.php?id=5&fn=ZmlsZXMvMjkzMTE1MzgwMTEuamFy&cs=1

Thanks.
