### ISSUE TITLE
Sign issues from mcredstonepro

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#45]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=390 (author: mcredstonepro) at Dec 24, 2012 at 05:51 UTC**

Hey, I am trying to create [BattleKits] Signs to give out kits, but there is a bug with it.
When I create a BattleKits sign, then right click it, it does NOT give the specified kit, not any kit to be exact. Instead, it gives in my inventory, only 1 empty soup bowl in the hotbar in the slot I right-click the sign with. Please fix this. Thanks.

**Comment by lol768** [comment]
What are you putting on the sign?
Config? Server log? Version? CB version?

**Comment by lol768** [comment]
Please refer to the https://github.com/np98765/BattleKits/issues/1 guidelines

**Comment by 45zeldafan** [comment]
Hey its mcredstonepro from bukkit. Anyway
This is what I put on the sign:
Line 1=[BattleKits]
Line 2=pvp
Line 3=_blank_
Line 4=_blank_

When I click done, in the chat it says the sign was successfully created. I right click the sign and it will say it gives me the kit, but only gives me a empty soup bowl.

Version of BattleKits: 1.9.1

**Comment by lol768** [comment]
Can I see your kit config?

**Comment by lol768** [comment]
Pastebin ensures proper formatting.

**Comment by 45zeldafan** [comment]
http://pastebin.com/raw.php?i=2FuB6h9H

**Comment by lol768** [comment]
please try this version:
http://pastebin.com/raw.php?i=pbC0Ld0t

If it still fails, please use the debug build:
http://199.241.30.86/builds/index.php

and give me the output

**Comment by JimBean** [comment]
Help my global.yml won't generate same as config.yml and kits.yml

**Comment by lol768** [comment]
@JimBean Please don't comment with your own problems on someone else's issue. Thanks

OP: Any luck with this?

**Comment by lol768** [comment]
Closing due to lack of response.
