### ISSUE TITLE
Plugin will not load (unsupported major.minor version)

### ISSUE THREAD

**Issue by an-empty-string** [np98765/BattleKits#46]
CraftBukkit version git-Bukkit-1.4.6-R0.1-11-g178daca-b2570jnks (MC: 1.4.6) (Implementing API version 1.4.6-R0.2-SNAPSHOT)

Plugins: WorldEdit, WorldGuard, Multiverse, CleanroomGenerator, and, of course, BattleKits

I'm running the "debug" version of BattleKits.

The error I'm getting is at http://pastebin.com/4vqEn944

**Comment by lol768** [comment]
Please update to Java 7.
