### ISSUE TITLE
Credit Reward System

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#48]
Hi, 
I know you said this could be a bit to far to add to this plugin I just wanted to explain how it would work anyways.

In the kit option a new line would be added named something along the lines of "diffcultly" you would enter a number between 1 - 10 for example 

so then you kit is equal to over powered you are, so if your really strong you would be diffcultly 1 so you would only get 1 credit per kill. if you where in a hard kit to use you would be diffcultly 10 you would get 10 credits per kill.

It would be easyer to add it to an existing econemy system such as essentials eco. 

more advanced updates could be added to make the system a lot better for example, if you hurt a player and he dies from another player within 5 - 10 seconds (could config the time), then you get 50% of the credits that player got aswell. again the percent could be setup in the config. 

So that way kill stealing rewards are fixed for players

Thanks!

**Comment by lol768** [comment]
Closed for now, but I might consider this in the future. For now, I still believe this is outside of the scope of the plugin.
