### ISSUE TITLE
UnSupported Major Minor version

### ISSUE THREAD

**Issue by lukeyc** [np98765/BattleKits#49]
Version: CB 1.4.6-R01
Major Plugins: Essentials, World guard, World edit, Permissionsex, Lwc , Factions
Version of plugin: the newest release for CB 1.4.6-R0.1
Config: Dose not make one :\
Error: I do not get the error any more in the console but it is Unsupported major minor version (I think this is because we have only java 1.5?) 
Im trying to use battle kits for my server :)

If you could recompile/rebuild the plugin for a older version of java that would be Awesome it looks like your plugin is by FAR the best kit one 

Thank you :D

**Comment by lol768** [comment]
Yes, this is a java version error. Unfortunately java 6 is outdated and in less than two months will be completely unsupported by oracle. It is also not as simple as compiling for java 6 as I use API methods only available with java 7. Can you tell me if this is home hosted, managed or hosted with a shared hosting company (e.g. BeastNode)? I may be able to assist in getting java updated for you.

EDIT: just noticed you're on jre 1.5 You should really update ASAP.

**Comment by lukeyc** [comment]
Wow ok thank you, it is hosted by Chicago VPS a remote vps hosting company.
Our server is runing Cent OS. Any tips on how to update? Thanks so much the plugin would fit my server and be EPIC thank you!

**Comment by lol768** [comment]
Try http://www.if-not-true-then-false.com/2010/install-sun-oracle-java-jdk-jre-7-on-fedora-centos-red-hat-rhel/
:smile:
