### ISSUE TITLE
Certain Area?

### ISSUE THREAD

**Issue by ghost** [np98765/BattleKits#5]
You could possibly hook into iZone, WorldGuard, or something similar to provide zone-only fights?

**Comment by lol768** [comment]
It's a possibility. I'll take a look at this idea after we've sorted any current bugs

**Comment by lol768** [comment]
WorldGuard allows zone-only kits with the /wg flag name allowed/disallowed-commands system and can also enable/disable PvP. Could you elaborate on what you'd like BattleKits to do that is different?

**Comment by lol768** [comment]
I'm gonna close this unless @Darky1126 explains further

**Comment by ghost** [comment]
It's fine, close it, and sorry I wasn't here to respond, I had no internet. (OKay, well I did, but it was 1.7Kb/s) -- Didn't know about that flag.

**Comment by lol768** [comment]
Thanks :)
