### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#50]
Hey,

Could we have some more information on how kits should be formatted I'm trying to add my own kits but there not working some kits have more spaces than others etc.. and I'm not sure how to do it :/

This is my current kits file - 
http://pastebin.com/zUyefrKj

and the scout kit will go on a sign but when I get the kit it doesnt give me any items from the kit, it also gives me the message setup in the kit. 

I tried loads of different spacing nothing seems to work :(

**Comment by lol768** [comment]
Can you removed the tag prefix bit? It tends to broke stuff at the moment - not sure why

**Comment by xron89** [comment]
Worked like a charm <3 

if I want to give players indivdual kits I can do a command such as "/manuaddp (username) (BattleKits.use.pyro)"
Thanks

**Comment by lol768** [comment]
Yep, that should do the trick I think

**Comment by xron89** [comment]
Last question i swear 

The last kit here "chemist" http://pastebin.com/ffzCJNFc

the sign creates okay but doesnt give me any item at all I haved removed the line you suggested before :/

**Comment by lol768** [comment]
The slots are formatted incorrectly. Let me find you a guide..

**Comment by lol768** [comment]
'itemID:amount:durability enchantmentID:level'

**Comment by lol768** [comment]
373:1:8257 is invalid
I assume you meant '373 1 8257'

**Comment by xron89** [comment]
so I was missing the " ' ' " marks

**Comment by xron89** [comment]
Now i'm confused because I have this on another class and it works fine - 
      '6': 373:1:8226
      '7': 373:1:8226
      '8': 373:1:8226

Giving speed potions

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/50#issuecomment-11764930

> Now i'm confused because I have this on another class and it works fine - 
>       '6': 373:1:8226
>       '7': 373:1:8226
>       '8': 373:1:8226
> Giving speed potions

it shouldn't work :smile:

You need SPACES instead of COLONS.

**Comment by xron89** [comment]
So on those ones I should add the ' ' marks? and remove the : and replace it with spaces?

**Comment by xron89** [comment]
so its 'potion ammount potionid'
or 
'potion:ammount:id'
:S AHHH

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/50#issuecomment-11764952

> so its 'potion ammount potionid'

Exactly.

e.g. 
'6': '373 1 8226'

**Comment by xron89** [comment]
Ahh thanks lemme give it a try and I will update old ones

**Comment by xron89** [comment]
Ahhh!! I did that now, theres loads of bugs, pick more than 1 kit per life, spam the same kit, potions dont show at all Ahhhh!!!

http://pastebin.com/fJr00i5U

**Comment by xron89** [comment]
So now - 

Mix kits, 
When you pick a kit you only get 1 item you have to relog to see all the items, 
potiosn dont shwo on any kits, 
multi kits per life 

I'm gonna leave this last kit try roll back a bit

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/50#issuecomment-11765083

> So now - 
> Mix kits, 
> When you pick a kit you only get 1 item you have to relog to see all the items, 
> potiosn dont shwo on any kits, 
> multi kits per life 
> I'm gonna leave this last kit try roll back a bit

I disabled one kit per life. You want it re-enabled?

" When you pick a kit you only get 1 item you have to relog to see all the items"

I'll check this in a sec

**Comment by xron89** [comment]
I would like them to switch kits, per life yeah but they keep one item from the old kit e.g. if they had slot 1 sleected on there hot bar they would keep that item from the last kit

**Comment by xron89** [comment]
Cries its all gone wrong again :(

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/50#issuecomment-11765120

> I would like them to switch kits, per life yeah but they keep one item from the old kit e.g. if they had slot 1 sleected on there hot bar they would keep that item from the last kit

Yeah, we don't allow that yet.

Feature request?

**Comment by xron89** [comment]
Okay, so I need to fix this so first off I need to stop them switching kits so is there a permission node for that?

**Comment by lol768** [comment]
Just enabled once-per-life now.

**Comment by xron89** [comment]
okay super thanks!! the only thing now is 3 of my kits are broken for no reason! thats "berserker" "scout" and "chemist" I dont think chemist will work because its mostly a potion kit so I might need to remove that one but the other two used to work :/
