### ISSUE TITLE
Some players can drop items, some not.

### ISSUE THREAD

**Issue by ja-silveira** [np98765/BattleKits#51]
Among those that can and can not, not any difference. But there are in the same group in Group Manger.
Permissions of default group:
  g:bukkit_default:
    permissions:
    - bukkit.broadcast.user
    - -bukkit.command.plugins
    - sg.arena.join
    - sg.arena.vote
    - sg.lobby.join
    - kitpvp.kit.pvp
    - kitpvp.kit.archer
    - essentials.warp
    - votekick.start
    - votekick.kick
    - paintball.general
    - essentials.kit
    - BattleKits.use.archer
    - BattleKits.use.heavy
    - BattleKits.bypassRestriction.disable-player-drops-on-death
    - BattleKits.bypassRestriction.disable-hunger
    - BattleKits.bypassRestriction.disable-player-drops-on-death
    - BattleKits.bypassRestriction.disable-crafting
    - BattleKits.bypassRestriction.disable-player-xp-drop
    - BattleKits.bypassRestriction.disable-mob-xp-drop
    - BattleKits.bypassRestriction.disable-block-xp
    - BattleKits.bypassRestriction.disable-inventory-interaction
    - BattleKits.bypassRestriction.disable-pickup-items
    - BattleKits.bypassRestriction.disable-block-break
    - BattleKits.bypassRestriction.disable-block-place
    - BattleKits.bypassRestriction.hide-death-messages
    - BattleKits.bypassRestriction.disable-inventory-click
    - buttoncommands.use.normal

My config:
# Global BattleKits settings
# Add world-specific blocks by warapping everything in the name of the world.
# Restrictions are handled by permissions now.

settings:
  once-per-life: false
  auto-update: false
  enable-restrictions: true
  show-kit-info-on-respawn: false
  override-disable-respawn-kits: false
  instant-soup-drink: false
instant-soup-drink:
  replenish-type: hunger
signs:
  ignore-permissions: false
  ignore-costs: false
  ignore-world-restriction: false
  ignore-lives-restriction: false
indirect:
  ignore-costs: false
  ignore-permissions: false
  ignore-world-restriction: false
  ignore-lives-restriction: false
rewards:
  killCommands:
- xp 1L <player>

My kits:

http://pastebin.com/Z8qxtNuW

**Comment by lol768** [comment]
Anyone who has the permissions `BattleKits.bypassRestriction.disable-dropping-items` will be able to drop them. I'd suggest negating that permission by puttin a dash in front of it.

**Comment by ja-silveira** [comment]
They don't have this permission.

**Comment by lol768** [comment]
I'll look into it, but so far tests have shown that there are no issues with the restriction system.
https://docs.google.com/a/infinitenight.net/spreadsheet/ccc?key=0Ai8_JDvk_gAjdHppTThrMFZ4RmdhVTBzZUR3a3QtMEE

What version are you using?
