### ISSUE TITLE
Soups wont heal health 

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#52]
Hi, This isn't an issue I have I joined a random kit server and it happend to be running battlekits and I tried to help them fix some things this is there issue they will watch this area for a fix- 

kit - 
http://pastebin.com/c4mfinXr

config - 
http://pastebin.com/uVQ5PA2i

**Comment by lol768** [comment]
Please dedent the instant-soup-drink part - it has a space in front of it.

**Comment by xron89** [comment]
Thanks sorted he says
