### ISSUE TITLE
Bowl when kits are given instead of actual items from Cheesea3

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#62]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=415 (author: Cheesea3) at Jan 01, 2013 at 19:19 UTC**

Yeah uhmm, sometimes my players pick a kit and all they get is a bowl... Also can you put some more kits on the forums? Like Scout ect. I made wizard on my own and I love it xD
This plugin is amazing I'll donate soon if I get some help with the bowl. It'd be nice to see more kits on forums.

**Comment by lol768** [comment]
Please give me the kit config file and all the other information specified here:
https://github.com/np98765/BattleKits/issues/1

**Comment by cheesea3** [comment]
WWW.YPEOPLESTEALMYKITCONFIGMAKEYOOWN.troll.cafe31.net
Sometimes randomly they get a bowl they have to killl there selves/relog ect to fix it.

**Comment by lol768** [comment]
Is there anything in the console when this happens? It sounds like the inventory is not updating properly.

**Comment by cheesea3** [comment]
Nothin' bad happening when hitting kit but sometimes it just gives you 1 bowl.

**Comment by lol768** [comment]
Is this with /kit or a kit sign?

**Comment by cheesea3** [comment]
Kit sign I believe so, yes.

**Comment by lol768** [comment]
Thanks, I'll look into it.

**Comment by xron89** [comment]
Just to note this also happens on my server randomly not everytime, sometimes a player will get a empty bowl instead of a kit, an easy fix is to get the player to relog. The kit has been given and other players can see the kti armour its just client side its very odd

**Comment by lol768** [comment]
Hmm, interesting - seems like it might be a Bukkit bug - what version of CB are you using?

**Comment by xron89** [comment]
the latest one

**Comment by cheesea3** [comment]
Hope this gets fixed :+1:

**Comment by lol768** [comment]
I'm thinking this might be an issue with Bukkit. My initial thoughts are to forcibly update the inventory after the kit has been given. This isn't directly my fault, but I can try to work around it.

**Comment by lol768** [comment]
Might be fixed in 2.0. If not, I'll reopen this and do some more work.

**Comment by kleinjan** [comment]
Hi cheesea3 I really love your server but when I tried logging in it told me that I'm not white-listed so I can't log in. Can you please help me

**Comment by cheesea3** [comment]
Yes, I actually have released it its not whitelisted now. We now have a new
server we changed the domain to redrict as a dns to the official ip so
connect using

kitpvpcc.com

**Comment by kleinjan** [comment]
Thanks if its not to much to ask can you please a kit with a diamond sword with a sharpness 4 enchantment but then you give no armor that would be nice

**Comment by cheesea3** [comment]
You still want that kit with a diamond sword with a sharpness 4 enchantmnet but then without armor? @kleinjan
