### ISSUE TITLE
Best suggestion ever!

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#65]
Theres a plugin called "potioncommands" and I want to give some effects to the kits, but for that the plugin only uses permission nodes.

So my suggestion is to run an optional command when a play picks a kit for example, 
PotionCommands.effect.fireresistance

Then pyro will be better, you need to add a way to remove the permission or the command run when a player dies though

**Comment by xron89** [comment]
Edit - just noticed you make that plugin wow! I think you already have added them together

**Comment by lol768** [comment]
PotionCommands works with commands :smile:

Add "potion <player> hunger 1000 1" as a kit command

**Comment by xron89** [comment]
kit commands dont exist yet though do they?

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/65#issuecomment-11928817

> kit commands dont exist yet though do they?

Yeah - they have for a while :grin:
https://github.com/np98765/BattleKits/blob/master/BattleKits/kits.yml#L7

**Comment by xron89** [comment]
Wait how I dont see it in any kit config?

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/65#issuecomment-11928863

> Wait how I dont see it in any kit config?

Take a look at the link I posted above, it gives you an example :smiley_cat:

**Comment by xron89** [comment]
my bad thanks

**Comment by xron89** [comment]
so this is correct usage?

"    commands: potion [user] Fire Resistance [duration]"

it gave the kit but not effect does it require a "/" 

this far now -     "commands: potion <player> Fire Resistance"
Dang it work!

**Comment by xron89** [comment]
Yeah I don't get it could you show a working example be more helpful than #Executed on kit give :S

**Comment by lol768** [comment]
Did you see the link? That was an example kit config with it in use. Just copy it.

``` yaml
    commands: #Executed on kit give
      - 'potion hunger 1000 1'
```
