### ISSUE TITLE
Add TagAPI for colored names when kit is given

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#7]
http://dev.bukkit.org/server-mods/tag/

**Comment by MapleFighter** [comment]
So is this implemented yet? It's a really great idea. TagAPI is great, I checked out a bunch of things about it and plugins that use it.

**Comment by lol768** [comment]
I'd like to to it sometime this weekend when I have some time.

**Comment by lol768** [comment]
Done, pending refresh issues

**Comment by MapleFighter** [comment]
Nice

**Comment by lol768** [comment]
Gonna close this.
