### ISSUE TITLE
Permissions issues from niknea

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#72]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=439 (author: niknea) at Jan 08, 2013 at 15:50 UTC**

Whenever someone picks a kit they can do /spawn and just abuse it and get thousand full iron. Also they can do /soup EVERWHERE on my server so they have unlimited soup. How do I stop that? Thanks!

**Comment by lol768** [comment]
How are you handing out kits? Signs? Or are you allowing them to use commands?

This sounds like permissions are not setup correctly.

Please refer to #1 - I need a lot more information to be able to help you.

Closing until more information is available...

**Comment by Niknea** [comment]
Yes I use signs. But when they click the sign they can just do /spawn right after that and get a bunch if gear. And the same with soup. They can do /soup with bowls and get a refill. Is it possible to make it when they leave the arena the items disappear? Thanks!

**Comment by lol768** [comment]
Please refer to #1 - I need a lot more information to be able to help you.

Please post your permissions config in addition to the information required above. I'll re-open the issue when I have this information available. Without this I cannot help you with the issue.

:lock:

**Comment by Niknea** [comment]
I didint give them any permissions but when they click the sign they can just do 
/spawn

**Comment by lol768** [comment]
Please refer to #1 - I need a lot more information to be able to help you.

Please post your permissions config in addition to the information required above. I'll re-open the issue when I have this information available. Without this I cannot help you with the issue.

Additionally, /spawn is not a command that BattleKits offers. Please attempt setting clearAll to true in your global.yml. It's really not up to me as to protecting your spawn area - this is something you need to do. It should be configured so that there is no way for the player to return to the spawn area.

:lock:
