### ISSUE TITLE
Why does BattleKits require Java 7? from saksham12345omfg

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#74]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=435 (author: saksham12345omfg) at Jan 07, 2013 at 20:15 UTC**

@np98765
@lol768
I still don't see how what java my computer has, has anything to do with the plugins i download for my home-hosted server... right now i have a Mac OS X Version 10.6.8, wont upgrading cost quite a bit of money?

**Comment by lol768** [comment]
Java 6 is nearing end of life in around a month. This means it will become completely unsupported. To counter this, and additionally due to the fact that I am using methods only available in Java 7 in BattleKits (all plugins use Java), I am unable and unwilling to compile with Java 6. I understand this is frustrating for users who are locked in to certain versions of Java, however I have no experience whatsoever with Mac OS X (I use Linux Mint) so I am unfortunately unable to tell you as to whether or not you need to pay in order to upgrade. 

I understand this answer is not very helpful for your particular situation and I can only suggest upgrading or changing OS (a suggestion which is likely unhelpful). Apologies, but this is really the best I can do :cry:

**Comment by np98765** [comment]
Mountain Lion, which is the only way to upgrade to Java 7 on a Mac, costs $20. It has some nifty other features, too.
