### ISSUE TITLE
Abusing

### ISSUE THREAD

**Issue by Niknea** [np98765/BattleKits#75]
Hello!  I use signs to let them get their kit. But when they click the sign they can just do /spawn right after that and get a bunch of gear. And the same with soup. They can do /soup with bowls and get a refill. Is it possible to make it when they leave the arena the items disappear? And they can't do /soup anywhere besides the arena? Thanks!

**Comment by lol768** [comment]
Duplicate issue.
https://github.com/np98765/BattleKits/issues/72
