### ISSUE TITLE
Null Pointer exeption

### ISSUE THREAD

**Issue by ja-silveira** [np98765/BattleKits#77]
My config: http://pastebin.com/Z4nfiL6u
Video: http://www.youtube.com/watch?v=Bf5v1LjVYQY&feature=youtu.be
Bukkit: 1.4.6 Relase 0.1 (Beta)
Error log: http://pastebin.com/xsuuNTEG
This happends only with kit Ninja.

**Comment by lol768** [comment]
373:1:8270 should be surrounded by single quotes.

**Comment by ja-silveira** [comment]
Still...
New config: http://pastebin.com/Q49kZ0EE

**Comment by lol768** [comment]
@zearthur99 https://github.com/np98765/BattleKits/issues/77#issuecomment-12098950

> Still...
> New config: http://pastebin.com/Q49kZ0EE

Essentials is interfering. Try using /bk instead

**Comment by ja-silveira** [comment]
Same problem with /bk and / battlekits

**Comment by lol768** [comment]
Can you try temporarily disabling essentials?

**Comment by ja-silveira** [comment]
I can't disable essentials. But i test on a local server with essentials and it works. Here is my list of plugins: http://i49.tinypic.com/25fswaf.png
