### ISSUE TITLE
Money query from rastus222

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#79]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=453 (author: rastus222) at Jan 10, 2013 at 22:32 UTC**

Would it be possible for you to make it so that if you have a money plugin like iconomy for you to get money from killing and you can buy kits so that you can have players kill and then get better kits?

**Comment by lol768** [comment]
This is indeed possible.

**Comment by lol768** [comment]
See cost setting for kits and death rewards (they allow any console command to be executed).

**Comment by ghost** [comment]
Have you figgured it out?
