### ISSUE TITLE
Enchant Support Expanded 

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#80]
Hey 
This plugin is working really well at the moment so happy it has got to this stage my server running this plugin hit 71 players last week, so I'm super happy! 

I would like the enchant support expanded e.g enchant a stick with sharpness or even a fish! There are existing plugins out there that do this already but I think when you try to enchant an item that isnt allowed an enchant like a fish or stick, the kit config breaks and all your kits break! 

Could you just remove the check for this or something so we can use custom enchants

**Comment by lol768** [comment]
I think you should be able to, but I'll be sure to look into it :smile:

**Comment by lol768** [comment]
Just checked the code and it appears you can in fact do this :smile:
