### ISSUE TITLE
Permissions for signs

### ISSUE THREAD

**Issue by mage1d** [np98765/BattleKits#82]
I have my server all setup and everything but every1 who is not op cant use the battlekit signs oplease help :P

**Comment by lol768** [comment]
Please follow the issue guidelines: #1

**Comment by mage1d** [comment]
Um no offence but i can't find it. (if you don't understand my question) the permissions like Battlekits.kit.kitname or whatever.

**Comment by lol768** [comment]
Give them `BattleKits.sign.use` and `BattleKits.use.kitName`
