### ISSUE TITLE
Mixing kits

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#85]
Hi,

You can mix kits again, when you go out and kill people randomly you will get the message (i think its random) you can now pick a kit again after you killed a player or more than one player. The person who killed a guy returns to spawn picks another kit thus mixing the kit because when a new kit is picked it doesn't clean the inventory of the player

**Comment by lol768** [comment]
Global config please

**Comment by xron89** [comment]
http://pastebin.com/mWGAwtK6 

here

**Comment by lol768** [comment]
Looks to be related to https://github.com/np98765/BattleKits/issues/62

**Comment by xron89** [comment]
is it hmm, they get a few kills then a message comes up you can now pick a kit so they can just type the command and mix between kits ;)

**Comment by lol768** [comment]
It's really odd, as if the inventory update code is broken.

**Comment by lol768** [comment]
Apologies for the massive delay in fixing this. Please update to 2.0 and this should be fixed.
