### ISSUE TITLE
No folder created on startup from denhut

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#94]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=511 (author: denhut) at Feb 12, 2013 at 01:30 UTC**

Hello, i have a Problem, i put the Jar file in my Plugin folder from the Server  and i restart/stop the Server but if the Server start new. But there create nox Battlekits FOlder. pls help thx

**Comment by lol768** [comment]
Can I see your server log file please?

Additionally, please ensure you are using Java 7.

**Comment by denhut** [comment]
okay buzt how can i send you the Log.

**Comment by denhut** [comment]
have you skype? you can add me sledge2.1

**Comment by denhut** [comment]
i have a idea why !! we habe the CB r1.1 is taht the Problem?

**Comment by lol768** [comment]
@denhut https://github.com/np98765/BattleKits/issues/94#issuecomment-13460773

> i have a idea why !! we habe the CB r1.1 is taht the Problem?

Yes.

**Comment by lol768** [comment]
@denhut https://github.com/np98765/BattleKits/issues/94#issuecomment-13460773

> i have a idea why !! we habe the CB r1.1 is taht the Problem?

Do you mean what I think I thought you meant? Are you running an older version of CraftBukkit than the latest recommended build?

Paste the log onto pastebin.com

**Comment by denhut** [comment]
i Use this 

1.4.7-R1.1  Development Build

**Comment by lol768** [comment]
Hmm, that shouldn't be a problem. Can I see your server log on pastebin please?

**Comment by denhut** [comment]
i have a problem i domt know how i can send you the server log, if i copie it on my desktop i become a error
