### ISSUE TITLE
battlekits error

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#97]
Hi,

I upgraded to 2.0 I cant perform any battlekit commands has the kit format changed? 

thanks i'll keep digging

**Comment by lol768** [comment]
Any stacktraces? Can I see your YAML file?

**Comment by xron89** [comment]
Sure, I have fixed a few issues, the only issue I have left now is OP can use all bk comamnds but players cant use signs etc.. 

here are the configs etc.. 

http://pastebin.com/n3gP9ewF - kits
http://pastebin.com/KaZikJZt - global
http://pastebin.com/KJc0c1P3 - permissions

**Comment by xron89** [comment]
any idea..

**Comment by lol768** [comment]
Wrap enchantments in single quotes........
